// ReSharper disable InconsistentNaming
#pragma warning disable 1591

namespace RGB.NET.Devices.SteelSeries;

/// <summary>
/// Contains a list of Steel Series LED IDs
/// </summary>
public enum SteelSeriesLedId
{
    [APIName("one")]
    ZoneOne,
    [APIName("two")]
    ZoneTwo,
    [APIName("three")]
    ZoneThree,
    [APIName("four")]
    ZoneFour,
    [APIName("five")]
    ZoneFive,
    [APIName("six")]
    ZoneSix,
    [APIName("seven")]
    ZoneSeven,
    [APIName("eight")]
    ZoneEight,
    [APIName("nine")]
    ZoneNine,
    [APIName("ten")]
    ZoneTen,
    [APIName("eleven")]
    ZoneEleven,
    [APIName("twelve")]
    ZoneTwelve,
    [APIName("thirteen")]
    ZoneThirteen,
    [APIName("fourteen")]
    ZoneFourteen,
    [APIName("fifteen")]
    ZoneFifteen,
    [APIName("sixteen")]
    ZoneSixteen,
    [APIName("seventeen")]
    ZoneSeventeen,
    [APIName("eighteen")]
    ZoneEighteen,
    [APIName("nineteen")]
    ZoneNineteen,
    [APIName("twenty")]
    ZoneTwenty,
    [APIName("twenty-one")]
    ZoneTwentyOne,
    [APIName("twenty-two")]
    ZoneTwentyTwo,
    [APIName("twenty-three")]
    ZoneTwentyThree,
    [APIName("twenty-four")]
    ZoneTwentyFour,
    [APIName("twenty-five")]
    ZoneTwentyFive,
    [APIName("twenty-six")]
    ZoneTwentySix,
    [APIName("twenty-seven")]
    ZoneTwentySeven,
    [APIName("twenty-eight")]
    ZoneTwentyEight,
    [APIName("twenty-nine")]
    ZoneTwentyNine,
    [APIName("thirty")]
    ZoneThirty,
    [APIName("thirty-one")]
    ZoneThirtyOne,
    [APIName("thirty-two")]
    ZoneThirtyTwo,
    [APIName("thirty-three")]
    ZoneThirtyThree,
    [APIName("thirty-four")]
    ZoneThirtyFour,
    [APIName("thirty-five")]
    ZoneThirtyFive,
    [APIName("thirty-six")]
    ZoneThirtySix,
    [APIName("thirty-seven")]
    ZoneThirtySeven,
    [APIName("thirty-eight")]
    ZoneThirtyEight,
    [APIName("thirty-nine")]
    ZoneThirtyNine,
    [APIName("forty")]
    ZoneForty,
    [APIName("forty-one")]
    ZoneFortyOne,
    [APIName("forty-two")]
    ZoneFortyTwo,
    [APIName("forty-three")]
    ZoneFortyThree,
    [APIName("forty-four")]
    ZoneFortyFour,
    [APIName("forty-five")]
    ZoneFortyFive,
    [APIName("forty-six")]
    ZoneFortySix,
    [APIName("forty-seven")]
    ZoneFortySeven,
    [APIName("forty-eight")]
    ZoneFortyEight,
    [APIName("forty-nine")]
    ZoneFortyNine,
    [APIName("fifty")]
    ZoneFifty,
    [APIName("fifty-one")]
    ZoneFiftyOne,
    [APIName("fifty-two")]
    ZoneFiftyTwo,
    [APIName("fifty-three")]
    ZoneFiftyThree,
    [APIName("fifty-four")]
    ZoneFiftyFour,
    [APIName("fifty-five")]
    ZoneFiftyFive,
    [APIName("fifty-six")]
    ZoneFiftySix,
    [APIName("fifty-seven")]
    ZoneFiftySeven,
    [APIName("fifty-eight")]
    ZoneFiftyEight,
    [APIName("fifty-nine")]
    ZoneFiftyNine,
    [APIName("sixty")]
    ZoneSixty,
    [APIName("sixty-one")]
    ZoneSixtyOne,
    [APIName("sixty-two")]
    ZoneSixtyTwo,
    [APIName("sixty-three")]
    ZoneSixtyThree,
    [APIName("sixty-four")]
    ZoneSixtyFour,
    [APIName("sixty-five")]
    ZoneSixtyFive,
    [APIName("sixty-six")]
    ZoneSixtySix,
    [APIName("sixty-seven")]
    ZoneSixtySeven,
    [APIName("sixty-eight")]
    ZoneSixtyEight,
    [APIName("sixty-nine")]
    ZoneSixtyNine,
    [APIName("seventy")]
    ZoneSeventy,
    [APIName("seventy-one")]
    ZoneSeventyOne,
    [APIName("seventy-two")]
    ZoneSeventyTwo,
    [APIName("seventy-three")]
    ZoneSeventyThree,
    [APIName("seventy-four")]
    ZoneSeventyFour,
    [APIName("seventy-five")]
    ZoneSeventyFive,
    [APIName("seventy-six")]
    ZoneSeventySix,
    [APIName("seventy-seven")]
    ZoneSeventySeven,
    [APIName("seventy-eight")]
    ZoneSeventyEight,
    [APIName("seventy-nine")]
    ZoneSeventyNine,
    [APIName("eighty")]
    ZoneEighty,
    [APIName("eighty-one")]
    ZoneEightyOne,
    [APIName("eighty-two")]
    ZoneEightyTwo,
    [APIName("eighty-three")]
    ZoneEightyThree,
    [APIName("eighty-four")]
    ZoneEightyFour,
    [APIName("eighty-five")]
    ZoneEightyFive,
    [APIName("eighty-six")]
    ZoneEightySix,
    [APIName("eighty-seven")]
    ZoneEightySeven,
    [APIName("eighty-eight")]
    ZoneEightyEight,
    [APIName("eighty-nine")]
    ZoneEightyNine,
    [APIName("ninety")]
    ZoneNinety,
    [APIName("ninety-one")]
    ZoneNinetyOne,
    [APIName("ninety-two")]
    ZoneNinetyTwo,
    [APIName("ninety-three")]
    ZoneNinetyThree,
    [APIName("ninety-four")]
    ZoneNinetyFour,
    [APIName("ninety-five")]
    ZoneNinetyFive,
    [APIName("ninety-six")]
    ZoneNinetySix,
    [APIName("ninety-seven")]
    ZoneNinetySeven,
    [APIName("ninety-eight")]
    ZoneNinetyEight,
    [APIName("ninety-nine")]
    ZoneNinetyNine,
    [APIName("one-hundred")]
    ZoneOneHundred,
    [APIName("one-hundred-one")]
    ZoneOneHundredOne,
    [APIName("one-hundred-two")]
    ZoneOneHundredTwo,
    [APIName("one-hundred-three")]
    ZoneOneHundredThree,

    [APIName("logo")]
    Logo,
    [APIName("a")]
    A,
    [APIName("b")]
    B,
    [APIName("c")]
    C,
    [APIName("d")]
    D,
    [APIName("e")]
    E,
    [APIName("f")]
    F,
    [APIName("g")]
    G,
    [APIName("h")]
    H,
    [APIName("i")]
    I,
    [APIName("j")]
    J,
    [APIName("k")]
    K,
    [APIName("l")]
    L,
    [APIName("m")]
    M,
    [APIName("n")]
    N,
    [APIName("o")]
    O,
    [APIName("p")]
    P,
    [APIName("q")]
    Q,
    [APIName("r")]
    R,
    [APIName("s")]
    S,
    [APIName("t")]
    T,
    [APIName("u")]
    U,
    [APIName("v")]
    V,
    [APIName("w")]
    W,
    [APIName("x")]
    X,
    [APIName("y")]
    Y,
    [APIName("z")]
    Z,
    [APIName("keyboard-1")]
    Keyboard1,
    [APIName("keyboard-2")]
    Keyboard2,
    [APIName("keyboard-3")]
    Keyboard3,
    [APIName("keyboard-4")]
    Keyboard4,
    [APIName("keyboard-5")]
    Keyboard5,
    [APIName("keyboard-6")]
    Keyboard6,
    [APIName("keyboard-7")]
    Keyboard7,
    [APIName("keyboard-8")]
    Keyboard8,
    [APIName("keyboard-9")]
    Keyboard9,
    [APIName("keyboard-0")]
    Keyboard0,
    [APIName("return")]
    Return,
    [APIName("escape")]
    Escape,
    [APIName("backspace")]
    Backspace,
    [APIName("tab")]
    Tab,
    [APIName("spacebar")]
    Spacebar,
    [APIName("caps")]
    Caps,
    [APIName("dash")]
    Dash,
    [APIName("equal")]
    Equal,
    [APIName("l-bracket")]
    LBracket,
    [APIName("r-bracket")]
    RBracket,
    [APIName("backslash")]
    Backslash,
    [APIName("pound")]
    Pound,
    [APIName("semicolon")]
    Semicolon,
    [APIName("quote")]
    Quote,
    [APIName("backquote")]
    Backqoute,
    [APIName("comma")]
    Comma,
    [APIName("period")]
    Period,
    [APIName("slash")]
    Slash,
    [APIName("f1")]
    F1,
    [APIName("f2")]
    F2,
    [APIName("f3")]
    F3,
    [APIName("f4")]
    F4,
    [APIName("f5")]
    F5,
    [APIName("f6")]
    F6,
    [APIName("f7")]
    F7,
    [APIName("f8")]
    F8,
    [APIName("f9")]
    F9,
    [APIName("f10")]
    F10,
    [APIName("f11")]
    F11,
    [APIName("f12")]
    F12,
    [APIName("printscreen")]
    PrintScreen,
    [APIName("scrolllock")]
    ScrollLock,
    [APIName("pause")]
    Pause,
    [APIName("insert")]
    Insert,
    [APIName("home")]
    Home,
    [APIName("pageup")]
    PageUp,
    [APIName("delete")]
    Delete,
    [APIName("end")]
    End,
    [APIName("pagedown")]
    PageDown,
    [APIName("rightarrow")]
    RightArrow,
    [APIName("leftarrow")]
    LeftArrow,
    [APIName("downarrow")]
    DownArrow,
    [APIName("uparrow")]
    UpArrow,
    [APIName("keypad-num-lock")]
    KeypadNumLock,
    [APIName("keypad-divide")]
    KeypadDivide,
    [APIName("keypad-times")]
    KeypadTimes,
    [APIName("keypad-minus")]
    KeypadMinus,
    [APIName("keypad-plus")]
    KeypadPlus,
    [APIName("keypad-enter")]
    KeypadEnter,
    [APIName("keypad-period")]
    KeypadPeriod,
    [APIName("keypad-1")]
    Keypad1,
    [APIName("keypad-2")]
    Keypad2,
    [APIName("keypad-3")]
    Keypad3,
    [APIName("keypad-4")]
    Keypad4,
    [APIName("num-5")] //HACK DarthAffe 07.10.2021: Custom name to workaround a SDK-issue (https://github.com/SteelSeries/gamesense-sdk/issues/85) should normally be 'keypad-5'
    Keypad5,
    [APIName("keypad-6")]
    Keypad6,
    [APIName("keypad-7")]
    Keypad7,
    [APIName("keypad-8")]
    Keypad8,
    [APIName("keypad-9")]
    Keypad9,
    [APIName("keypad-0")]
    Keypad0,
    [APIName("l-ctrl")]
    LCtrl,
    [APIName("l-shift")]
    LShift,
    [APIName("l-alt")]
    LAlt,
    [APIName("l-win")]
    LWin,
    [APIName("r-ctrl")]
    RCtrl,
    [APIName("r-shift")]
    RShift,
    [APIName("r-alt")]
    RAlt,
    [APIName("r-win")]
    RWin,
    [APIName("ss-key")]
    SSKey,
    [APIName("win-menu")]
    WinMenu,
    [APIName("m0")]
    M0,
    [APIName("m1")]
    M1,
    [APIName("m2")]
    M2,
    [APIName("m3")]
    M3,
    [APIName("m4")]
    M4,
    [APIName("m5")]
    M5,
}