namespace RGB.NET.Devices.SteelSeries
{
    public enum SteelSeriesLedId
    {
        [APIName("one")]
        ZoneOne,
        [APIName("two")]
        ZoneTwo,
        [APIName("three")]
        ZoneThree,
        [APIName("four")]
        ZoneFour,
        [APIName("five")]
        ZoneFive,
        [APIName("six")]
        ZoneSix,
        [APIName("seven")]
        ZoneSeven,
        [APIName("eight")]
        ZoneEight,
        [APIName("nine")]
        ZoneNine,
        [APIName("ten")]
        ZoneTen,

        [APIName("logo")]
        Logo,
        [APIName("a")]
        A,
        [APIName("b")]
        B,
        [APIName("c")]
        C,
        [APIName("d")]
        D,
        [APIName("e")]
        E,
        [APIName("f")]
        F,
        [APIName("g")]
        G,
        [APIName("h")]
        H,
        [APIName("i")]
        I,
        [APIName("j")]
        J,
        [APIName("k")]
        K,
        [APIName("l")]
        L,
        [APIName("m")]
        M,
        [APIName("n")]
        N,
        [APIName("o")]
        O,
        [APIName("p")]
        P,
        [APIName("q")]
        Q,
        [APIName("r")]
        R,
        [APIName("s")]
        S,
        [APIName("t")]
        T,
        [APIName("u")]
        U,
        [APIName("v")]
        V,
        [APIName("w")]
        W,
        [APIName("x")]
        X,
        [APIName("y")]
        Y,
        [APIName("z")]
        Z,
        [APIName("keyboard-1")]
        Keyboard1,
        [APIName("keyboard-2")]
        Keyboard2,
        [APIName("keyboard-3")]
        Keyboard3,
        [APIName("keyboard-4")]
        Keyboard4,
        [APIName("keyboard-5")]
        Keyboard5,
        [APIName("keyboard-6")]
        Keyboard6,
        [APIName("keyboard-7")]
        Keyboard7,
        [APIName("keyboard-8")]
        Keyboard8,
        [APIName("keyboard-9")]
        Keyboard9,
        [APIName("keyboard-0")]
        Keyboard0,
        [APIName("return")]
        Return,
        [APIName("escape")]
        Escape,
        [APIName("backspace")]
        Backspace,
        [APIName("tab")]
        Tab,
        [APIName("spacebar")]
        Spacebar,
        [APIName("caps")]
        Caps,
        [APIName("dash")]
        Dash,
        [APIName("equal")]
        Equal,
        [APIName("l-bracket")]
        LBracket,
        [APIName("r-bracket")]
        RBracket,
        [APIName("backslash")]
        Backslash,
        [APIName("pound")]
        Pound,
        [APIName("semicolon")]
        Semicolon,
        [APIName("quote")]
        Quote,
        [APIName("backquote")]
        Backqoute,
        [APIName("comma")]
        Comma,
        [APIName("period")]
        Period,
        [APIName("slash")]
        Slash,
        [APIName("f1")]
        F1,
        [APIName("f2")]
        F2,
        [APIName("f3")]
        F3,
        [APIName("f4")]
        F4,
        [APIName("f5")]
        F5,
        [APIName("f6")]
        F6,
        [APIName("f7")]
        F7,
        [APIName("f8")]
        F8,
        [APIName("f9")]
        F9,
        [APIName("f10")]
        F10,
        [APIName("f11")]
        F11,
        [APIName("f12")]
        F12,
        [APIName("printscreen")]
        PrintScreen,
        [APIName("scrolllock")]
        ScrollLock,
        [APIName("pause")]
        Pause,
        [APIName("insert")]
        Insert,
        [APIName("home")]
        Home,
        [APIName("pageup")]
        PageUp,
        [APIName("delete")]
        Delete,
        [APIName("end")]
        End,
        [APIName("pagedown")]
        PageDown,
        [APIName("rightarrow")]
        RightArrow,
        [APIName("leftarrow")]
        LeftArrow,
        [APIName("downarrow")]
        DownArrow,
        [APIName("uparrow")]
        UpArrow,
        [APIName("keypad-num-lock")]
        KeypadNumLock,
        [APIName("keypad-divide")]
        KeypadDivide,
        [APIName("keypad-times")]
        KeypadTimes,
        [APIName("keypad-minus")]
        KeypadMinus,
        [APIName("keypad-plus")]
        KeypadPlus,
        [APIName("keypad-enter")]
        KeypadEnter,
        [APIName("keypad-period")]
        KeypadPeriod,
        [APIName("keypad-1")]
        Keypad1,
        [APIName("keypad-2")]
        Keypad2,
        [APIName("keypad-3")]
        Keypad3,
        [APIName("keypad-4")]
        Keypad4,
        [APIName("keypad-5")]
        Keypad5,
        [APIName("keypad-6")]
        Keypad6,
        [APIName("keypad-7")]
        Keypad7,
        [APIName("keypad-8")]
        Keypad8,
        [APIName("keypad-9")]
        Keypad9,
        [APIName("keypad-0")]
        Keypad0,
        [APIName("l-ctrl")]
        LCtrl,
        [APIName("l-shift")]
        LShift,
        [APIName("l-alt")]
        LAlt,
        [APIName("l-win")]
        LWin,
        [APIName("r-ctrl")]
        RCtrl,
        [APIName("r-shift")]
        RShift,
        [APIName("r-alt")]
        RAlt,
        [APIName("r-win")]
        RWin,
        [APIName("ss-key")]
        SSKey,
        [APIName("win-menu")]
        WinMenu,
        [APIName("m0")]
        M0,
        [APIName("m1")]
        M1,
        [APIName("m2")]
        M2,
        [APIName("m3")]
        M3,
        [APIName("m4")]
        M4,
        [APIName("m5")]
        M5,
    }
}
