// ReSharper disable InconsistentNaming

using System.Collections.Generic;
using RGB.NET.Core;

namespace RGB.NET.Devices.CoolerMaster
{
    /// <summary>
    /// Contains all the hardware-id mappings for CoolerMaster devices.
    /// </summary>
    internal static class CoolerMasterKeyboardLedMappings
    {
        #region Properties & Fields

        #region MasterKeysL

        private static readonly Dictionary<LedId, (int row, int column)> MasterKeysL_US = new Dictionary<LedId, (int row, int column)>
        {
            { LedId.Keyboard_Escape, (0,0) },
            { LedId.Keyboard_F1, (0,1) },
            { LedId.Keyboard_F2, (0,2) },
            { LedId.Keyboard_F3, (0,3) },
            { LedId.Keyboard_F4, (0,4) },
            { LedId.Keyboard_F5, (0,6) },
            { LedId.Keyboard_F6, (0,7) },
            { LedId.Keyboard_F7, (0,8) },
            { LedId.Keyboard_F8, (0,9) },
            { LedId.Keyboard_F9, (0,11) },
            { LedId.Keyboard_F10, (0,12) },
            { LedId.Keyboard_F11, (0,13) },
            { LedId.Keyboard_F12, (0,14) },
            { LedId.Keyboard_PrintScreen, (0,15) },
            { LedId.Keyboard_ScrollLock, (0,16) },
            { LedId.Keyboard_PauseBreak, (0,17) },
            { LedId.Keyboard_Programmable1, (0,18) },
            { LedId.Keyboard_Programmable2, (0,19) },
            { LedId.Keyboard_Programmable3, (0,20) },
            { LedId.Keyboard_Programmable4, (0,21) },

            { LedId.Keyboard_GraveAccentAndTilde, (1,0) },
            { LedId.Keyboard_1, (1,1) },
            { LedId.Keyboard_2, (1,2) },
            { LedId.Keyboard_3, (1,3) },
            { LedId.Keyboard_4, (1,4) },
            { LedId.Keyboard_5, (1,5) },
            { LedId.Keyboard_6, (1,6) },
            { LedId.Keyboard_7, (1,7) },
            { LedId.Keyboard_8, (1,8) },
            { LedId.Keyboard_9, (1,9) },
            { LedId.Keyboard_0, (1,10) },
            { LedId.Keyboard_MinusAndUnderscore, (1,11) },
            { LedId.Keyboard_EqualsAndPlus, (1,12) },
            { LedId.Keyboard_Backspace, (1,14) },
            { LedId.Keyboard_Insert, (1,15) },
            { LedId.Keyboard_Home, (1,16) },
            { LedId.Keyboard_PageUp, (1,17) },
            { LedId.Keyboard_NumLock, (1,18) },
            { LedId.Keyboard_NumSlash, (1,19) },
            { LedId.Keyboard_NumAsterisk, (1,20) },
            { LedId.Keyboard_NumMinus, (1,21) },

            { LedId.Keyboard_Tab, (2,0) },
            { LedId.Keyboard_Q, (2,1) },
            { LedId.Keyboard_W, (2,2) },
            { LedId.Keyboard_E, (2,3) },
            { LedId.Keyboard_R, (2,4) },
            { LedId.Keyboard_T, (2,5) },
            { LedId.Keyboard_Y, (2,6) },
            { LedId.Keyboard_U, (2,7) },
            { LedId.Keyboard_I, (2,8) },
            { LedId.Keyboard_O, (2,9) },
            { LedId.Keyboard_P, (2,10) },
            { LedId.Keyboard_BracketLeft, (2,11) },
            { LedId.Keyboard_BracketRight, (2,12) },
            { LedId.Keyboard_Backslash, (2,14) },
            { LedId.Keyboard_Delete, (2,15) },
            { LedId.Keyboard_End, (2,16) },
            { LedId.Keyboard_PageDown, (2,17) },
            { LedId.Keyboard_Num7, (2,18) },
            { LedId.Keyboard_Num8, (2,19) },
            { LedId.Keyboard_Num9, (2,20) },
            { LedId.Keyboard_NumPlus, (2,21) },

            { LedId.Keyboard_CapsLock, (3,0) },
            { LedId.Keyboard_A, (3,1) },
            { LedId.Keyboard_S, (3,2) },
            { LedId.Keyboard_D, (3,3) },
            { LedId.Keyboard_F, (3,4) },
            { LedId.Keyboard_G, (3,5) },
            { LedId.Keyboard_H, (3,6) },
            { LedId.Keyboard_J, (3,7) },
            { LedId.Keyboard_K, (3,8) },
            { LedId.Keyboard_L, (3,9) },
            { LedId.Keyboard_SemicolonAndColon, (3,10) },
            { LedId.Keyboard_ApostropheAndDoubleQuote, (3,11) },
            { LedId.Keyboard_Enter, (3,14) },
            { LedId.Keyboard_Num4, (3,18) },
            { LedId.Keyboard_Num5, (3,19) },
            { LedId.Keyboard_Num6, (3,20) },

            { LedId.Keyboard_LeftShift, (4,0) },
            { LedId.Keyboard_Z, (4,2) },
            { LedId.Keyboard_X, (4,3) },
            { LedId.Keyboard_C, (4,4) },
            { LedId.Keyboard_V, (4,5) },
            { LedId.Keyboard_B, (4,6) },
            { LedId.Keyboard_N, (4,7) },
            { LedId.Keyboard_M, (4,8) },
            { LedId.Keyboard_CommaAndLessThan, (4,9) },
            { LedId.Keyboard_PeriodAndBiggerThan, (4,10) },
            { LedId.Keyboard_SlashAndQuestionMark, (4,11) },
            { LedId.Keyboard_RightShift, (4,14) },
            { LedId.Keyboard_ArrowUp, (4,16) },
            { LedId.Keyboard_Num1, (4,18) },
            { LedId.Keyboard_Num2, (4,19) },
            { LedId.Keyboard_Num3, (4,20) },
            { LedId.Keyboard_NumEnter, (4,21) },

            { LedId.Keyboard_LeftCtrl, (5,0) },
            { LedId.Keyboard_LeftGui, (5,1) },
            { LedId.Keyboard_LeftAlt, (5,2) },
            { LedId.Keyboard_Space, (5,6) },
            { LedId.Keyboard_RightAlt, (5,10) },
            { LedId.Keyboard_RightGui, (5,11) },
            { LedId.Keyboard_Application, (5,12) },
            { LedId.Keyboard_RightCtrl, (5,14) },
            { LedId.Keyboard_ArrowLeft, (5,15) },
            { LedId.Keyboard_ArrowDown, (5,16) },
            { LedId.Keyboard_ArrowRight, (5,17) },
            { LedId.Keyboard_Num0, (5,18) },
            { LedId.Keyboard_NumPeriodAndDelete, (5,20) }
        };

        private static readonly Dictionary<LedId, (int row, int column)> MasterKeysL_EU = new Dictionary<LedId, (int row, int column)>
        {
            { LedId.Keyboard_Escape, (0,0) },
            { LedId.Keyboard_F1, (0,1) },
            { LedId.Keyboard_F2, (0,2) },
            { LedId.Keyboard_F3, (0,3) },
            { LedId.Keyboard_F4, (0,4) },
            { LedId.Keyboard_F5, (0,6) },
            { LedId.Keyboard_F6, (0,7) },
            { LedId.Keyboard_F7, (0,8) },
            { LedId.Keyboard_F8, (0,9) },
            { LedId.Keyboard_F9, (0,11) },
            { LedId.Keyboard_F10, (0,12) },
            { LedId.Keyboard_F11, (0,13) },
            { LedId.Keyboard_F12, (0,14) },
            { LedId.Keyboard_PrintScreen, (0,15) },
            { LedId.Keyboard_ScrollLock, (0,16) },
            { LedId.Keyboard_PauseBreak, (0,17) },
            { LedId.Keyboard_Programmable1, (0,18) },
            { LedId.Keyboard_Programmable2, (0,19) },
            { LedId.Keyboard_Programmable3, (0,20) },
            { LedId.Keyboard_Programmable4, (0,21) },

            { LedId.Keyboard_GraveAccentAndTilde, (1,0) },
            { LedId.Keyboard_1, (1,1) },
            { LedId.Keyboard_2, (1,2) },
            { LedId.Keyboard_3, (1,3) },
            { LedId.Keyboard_4, (1,4) },
            { LedId.Keyboard_5, (1,5) },
            { LedId.Keyboard_6, (1,6) },
            { LedId.Keyboard_7, (1,7) },
            { LedId.Keyboard_8, (1,8) },
            { LedId.Keyboard_9, (1,9) },
            { LedId.Keyboard_0, (1,10) },
            { LedId.Keyboard_MinusAndUnderscore, (1,11) },
            { LedId.Keyboard_EqualsAndPlus, (1,12) },
            { LedId.Keyboard_Backspace, (1,14) },
            { LedId.Keyboard_Insert, (1,15) },
            { LedId.Keyboard_Home, (1,16) },
            { LedId.Keyboard_PageUp, (1,17) },
            { LedId.Keyboard_NumLock, (1,18) },
            { LedId.Keyboard_NumSlash, (1,19) },
            { LedId.Keyboard_NumAsterisk, (1,20) },
            { LedId.Keyboard_NumMinus, (1,21) },

            { LedId.Keyboard_Tab, (2,0) },
            { LedId.Keyboard_Q, (2,1) },
            { LedId.Keyboard_W, (2,2) },
            { LedId.Keyboard_E, (2,3) },
            { LedId.Keyboard_R, (2,4) },
            { LedId.Keyboard_T, (2,5) },
            { LedId.Keyboard_Y, (2,6) },
            { LedId.Keyboard_U, (2,7) },
            { LedId.Keyboard_I, (2,8) },
            { LedId.Keyboard_O, (2,9) },
            { LedId.Keyboard_P, (2,10) },
            { LedId.Keyboard_BracketLeft, (2,11) },
            { LedId.Keyboard_BracketRight, (2,12) },
            { LedId.Keyboard_Enter, (2,14) },
            { LedId.Keyboard_Delete, (2,15) },
            { LedId.Keyboard_End, (2,16) },
            { LedId.Keyboard_PageDown, (2,17) },
            { LedId.Keyboard_Num7, (2,18) },
            { LedId.Keyboard_Num8, (2,19) },
            { LedId.Keyboard_Num9, (2,20) },
            { LedId.Keyboard_NumPlus, (2,21) },

            { LedId.Keyboard_CapsLock, (3,0) },
            { LedId.Keyboard_A, (3,1) },
            { LedId.Keyboard_S, (3,2) },
            { LedId.Keyboard_D, (3,3) },
            { LedId.Keyboard_F, (3,4) },
            { LedId.Keyboard_G, (3,5) },
            { LedId.Keyboard_H, (3,6) },
            { LedId.Keyboard_J, (3,7) },
            { LedId.Keyboard_K, (3,8) },
            { LedId.Keyboard_L, (3,9) },
            { LedId.Keyboard_SemicolonAndColon, (3,10) },
            { LedId.Keyboard_ApostropheAndDoubleQuote, (3,11) },
            { LedId.Keyboard_NonUsTilde, (3,12) },
            { LedId.Keyboard_Num4, (3,18) },
            { LedId.Keyboard_Num5, (3,19) },
            { LedId.Keyboard_Num6, (3,20) },

            { LedId.Keyboard_LeftShift, (4,0) },
            { LedId.Keyboard_NonUsBackslash, (4,1) },
            { LedId.Keyboard_Z, (4,2) },
            { LedId.Keyboard_X, (4,3) },
            { LedId.Keyboard_C, (4,4) },
            { LedId.Keyboard_V, (4,5) },
            { LedId.Keyboard_B, (4,6) },
            { LedId.Keyboard_N, (4,7) },
            { LedId.Keyboard_M, (4,8) },
            { LedId.Keyboard_CommaAndLessThan, (4,9) },
            { LedId.Keyboard_PeriodAndBiggerThan, (4,10) },
            { LedId.Keyboard_SlashAndQuestionMark, (4,11) },
            { LedId.Keyboard_RightShift, (4,14) },
            { LedId.Keyboard_ArrowUp, (4,16) },
            { LedId.Keyboard_Num1, (4,18) },
            { LedId.Keyboard_Num2, (4,19) },
            { LedId.Keyboard_Num3, (4,20) },
            { LedId.Keyboard_NumEnter, (4,21) },

            { LedId.Keyboard_LeftCtrl, (5,0) },
            { LedId.Keyboard_LeftGui, (5,1) },
            { LedId.Keyboard_LeftAlt, (5,2) },
            { LedId.Keyboard_Space, (5,6) },
            { LedId.Keyboard_RightAlt, (5,10) },
            { LedId.Keyboard_RightGui, (5,11) },
            { LedId.Keyboard_Application, (5,12) },
            { LedId.Keyboard_RightCtrl, (5,14) },
            { LedId.Keyboard_ArrowLeft, (5,15) },
            { LedId.Keyboard_ArrowDown, (5,16) },
            { LedId.Keyboard_ArrowRight, (5,17) },
            { LedId.Keyboard_Num0, (5,18) },
            { LedId.Keyboard_NumPeriodAndDelete, (5,20) }
        };

        #endregion

        #region MasterKeysM

        private static readonly Dictionary<LedId, (int row, int column)> MasterKeysM_US = new Dictionary<LedId, (int row, int column)>
        {
            { LedId.Keyboard_Escape, (0,0) },
            { LedId.Keyboard_F1, (0,1) },
            { LedId.Keyboard_F2, (0,2) },
            { LedId.Keyboard_F3, (0,3) },
            { LedId.Keyboard_F4, (0,4) },
            { LedId.Keyboard_F5, (0,6) },
            { LedId.Keyboard_F6, (0,7) },
            { LedId.Keyboard_F7, (0,8) },
            { LedId.Keyboard_F8, (0,9) },
            { LedId.Keyboard_F9, (0,11) },
            { LedId.Keyboard_F10, (0,12) },
            { LedId.Keyboard_F11, (0,13) },
            { LedId.Keyboard_F12, (0,14) },

            { LedId.Keyboard_GraveAccentAndTilde, (1,0) },
            { LedId.Keyboard_1, (1,1) },
            { LedId.Keyboard_2, (1,2) },
            { LedId.Keyboard_3, (1,3) },
            { LedId.Keyboard_4, (1,4) },
            { LedId.Keyboard_5, (1,5) },
            { LedId.Keyboard_6, (1,6) },
            { LedId.Keyboard_7, (1,7) },
            { LedId.Keyboard_8, (1,8) },
            { LedId.Keyboard_9, (1,9) },
            { LedId.Keyboard_0, (1,10) },
            { LedId.Keyboard_MinusAndUnderscore, (1,11) },
            { LedId.Keyboard_EqualsAndPlus, (1,12) },
            { LedId.Keyboard_Backspace, (1,14) },
            { LedId.Keyboard_NumLock, (1,15) },
            { LedId.Keyboard_NumSlash, (1,16) },
            { LedId.Keyboard_NumAsterisk, (1,17) },
            { LedId.Keyboard_NumMinus, (1,18) },

            { LedId.Keyboard_Tab, (2,0) },
            { LedId.Keyboard_Q, (2,1) },
            { LedId.Keyboard_W, (2,2) },
            { LedId.Keyboard_E, (2,3) },
            { LedId.Keyboard_R, (2,4) },
            { LedId.Keyboard_T, (2,5) },
            { LedId.Keyboard_Y, (2,6) },
            { LedId.Keyboard_U, (2,7) },
            { LedId.Keyboard_I, (2,8) },
            { LedId.Keyboard_O, (2,9) },
            { LedId.Keyboard_P, (2,10) },
            { LedId.Keyboard_BracketLeft, (2,11) },
            { LedId.Keyboard_BracketRight, (2,12) },
            { LedId.Keyboard_Backslash, (2,14) },
            { LedId.Keyboard_Num7, (2,15) },
            { LedId.Keyboard_Num8, (2,16) },
            { LedId.Keyboard_Num9, (2,17) },
            { LedId.Keyboard_NumPlus, (2,18) },

            { LedId.Keyboard_CapsLock, (3,0) },
            { LedId.Keyboard_A, (3,1) },
            { LedId.Keyboard_S, (3,2) },
            { LedId.Keyboard_D, (3,3) },
            { LedId.Keyboard_F, (3,4) },
            { LedId.Keyboard_G, (3,5) },
            { LedId.Keyboard_H, (3,6) },
            { LedId.Keyboard_J, (3,7) },
            { LedId.Keyboard_K, (3,8) },
            { LedId.Keyboard_L, (3,9) },
            { LedId.Keyboard_SemicolonAndColon, (3,10) },
            { LedId.Keyboard_ApostropheAndDoubleQuote, (3,11) },
            { LedId.Keyboard_Enter, (3,14) },
            { LedId.Keyboard_Num4, (3,15) },
            { LedId.Keyboard_Num5, (3,16) },
            { LedId.Keyboard_Num6, (3,17) },

            { LedId.Keyboard_LeftShift, (4,0) },
            { LedId.Keyboard_Z, (4,2) },
            { LedId.Keyboard_X, (4,3) },
            { LedId.Keyboard_C, (4,4) },
            { LedId.Keyboard_V, (4,5) },
            { LedId.Keyboard_B, (4,6) },
            { LedId.Keyboard_N, (4,7) },
            { LedId.Keyboard_M, (4,8) },
            { LedId.Keyboard_CommaAndLessThan, (4,9) },
            { LedId.Keyboard_PeriodAndBiggerThan, (4,10) },
            { LedId.Keyboard_SlashAndQuestionMark, (4,11) },
            { LedId.Keyboard_RightShift, (4,14) },
            { LedId.Keyboard_Num1, (4,15) },
            { LedId.Keyboard_Num2, (4,16) },
            { LedId.Keyboard_Num3, (4,17) },
            { LedId.Keyboard_NumEnter, (4,18) },

            { LedId.Keyboard_LeftCtrl, (5,0) },
            { LedId.Keyboard_LeftGui, (5,1) },
            { LedId.Keyboard_LeftAlt, (5,2) },
            { LedId.Keyboard_Space, (5,6) },
            { LedId.Keyboard_RightAlt, (5,10) },
            { LedId.Keyboard_RightGui, (5,11) },
            { LedId.Keyboard_Application, (5,12) },
            { LedId.Keyboard_RightCtrl, (5,14) },
            { LedId.Keyboard_Num0, (5,15) },
            { LedId.Keyboard_Num00, (5,16) },
            { LedId.Keyboard_NumPeriodAndDelete, (5,17) }
        };

        private static readonly Dictionary<LedId, (int row, int column)> MasterKeysM_EU = new Dictionary<LedId, (int row, int column)>
        {
            { LedId.Keyboard_Escape, (0,0) },
            { LedId.Keyboard_F1, (0,1) },
            { LedId.Keyboard_F2, (0,2) },
            { LedId.Keyboard_F3, (0,3) },
            { LedId.Keyboard_F4, (0,4) },
            { LedId.Keyboard_F5, (0,6) },
            { LedId.Keyboard_F6, (0,7) },
            { LedId.Keyboard_F7, (0,8) },
            { LedId.Keyboard_F8, (0,9) },
            { LedId.Keyboard_F9, (0,11) },
            { LedId.Keyboard_F10, (0,12) },
            { LedId.Keyboard_F11, (0,13) },
            { LedId.Keyboard_F12, (0,14) },

            { LedId.Keyboard_GraveAccentAndTilde, (1,0) },
            { LedId.Keyboard_1, (1,1) },
            { LedId.Keyboard_2, (1,2) },
            { LedId.Keyboard_3, (1,3) },
            { LedId.Keyboard_4, (1,4) },
            { LedId.Keyboard_5, (1,5) },
            { LedId.Keyboard_6, (1,6) },
            { LedId.Keyboard_7, (1,7) },
            { LedId.Keyboard_8, (1,8) },
            { LedId.Keyboard_9, (1,9) },
            { LedId.Keyboard_0, (1,10) },
            { LedId.Keyboard_MinusAndUnderscore, (1,11) },
            { LedId.Keyboard_EqualsAndPlus, (1,12) },
            { LedId.Keyboard_Backspace, (1,14) },
            { LedId.Keyboard_NumLock, (1,15) },
            { LedId.Keyboard_NumSlash, (1,16) },
            { LedId.Keyboard_NumAsterisk, (1,17) },
            { LedId.Keyboard_NumMinus, (1,18) },

            { LedId.Keyboard_Tab, (2,0) },
            { LedId.Keyboard_Q, (2,1) },
            { LedId.Keyboard_W, (2,2) },
            { LedId.Keyboard_E, (2,3) },
            { LedId.Keyboard_R, (2,4) },
            { LedId.Keyboard_T, (2,5) },
            { LedId.Keyboard_Y, (2,6) },
            { LedId.Keyboard_U, (2,7) },
            { LedId.Keyboard_I, (2,8) },
            { LedId.Keyboard_O, (2,9) },
            { LedId.Keyboard_P, (2,10) },
            { LedId.Keyboard_BracketLeft, (2,11) },
            { LedId.Keyboard_BracketRight, (2,12) },
            { LedId.Keyboard_Backslash, (2,14) },
            { LedId.Keyboard_Num7, (2,15) },
            { LedId.Keyboard_Num8, (2,16) },
            { LedId.Keyboard_Num9, (2,17) },
            { LedId.Keyboard_NumPlus, (2,18) },

            { LedId.Keyboard_CapsLock, (3,0) },
            { LedId.Keyboard_A, (3,1) },
            { LedId.Keyboard_S, (3,2) },
            { LedId.Keyboard_D, (3,3) },
            { LedId.Keyboard_F, (3,4) },
            { LedId.Keyboard_G, (3,5) },
            { LedId.Keyboard_H, (3,6) },
            { LedId.Keyboard_J, (3,7) },
            { LedId.Keyboard_K, (3,8) },
            { LedId.Keyboard_L, (3,9) },
            { LedId.Keyboard_SemicolonAndColon, (3,10) },
            { LedId.Keyboard_ApostropheAndDoubleQuote, (3,11) },
            { LedId.Keyboard_NonUsTilde, (3,12) },
            { LedId.Keyboard_Num4, (3,15) },
            { LedId.Keyboard_Num5, (3,16) },
            { LedId.Keyboard_Num6, (3,17) },

            { LedId.Keyboard_LeftShift, (4,0) },
            { LedId.Keyboard_NonUsBackslash, (4,1) },
            { LedId.Keyboard_Z, (4,2) },
            { LedId.Keyboard_X, (4,3) },
            { LedId.Keyboard_C, (4,4) },
            { LedId.Keyboard_V, (4,5) },
            { LedId.Keyboard_B, (4,6) },
            { LedId.Keyboard_N, (4,7) },
            { LedId.Keyboard_M, (4,8) },
            { LedId.Keyboard_CommaAndLessThan, (4,9) },
            { LedId.Keyboard_PeriodAndBiggerThan, (4,10) },
            { LedId.Keyboard_SlashAndQuestionMark, (4,11) },
            { LedId.Keyboard_RightShift, (4,14) },
            { LedId.Keyboard_Num1, (4,15) },
            { LedId.Keyboard_Num2, (4,16) },
            { LedId.Keyboard_Num3, (4,17) },
            { LedId.Keyboard_NumEnter, (4,18) },

            { LedId.Keyboard_LeftCtrl, (5,0) },
            { LedId.Keyboard_LeftGui, (5,1) },
            { LedId.Keyboard_LeftAlt, (5,2) },
            { LedId.Keyboard_Space, (5,6) },
            { LedId.Keyboard_RightAlt, (5,10) },
            { LedId.Keyboard_RightGui, (5,11) },
            { LedId.Keyboard_Application, (5,12) },
            { LedId.Keyboard_RightCtrl, (5,14) },
            { LedId.Keyboard_Num0, (5,15) },
            { LedId.Keyboard_Num00, (5,16) },
            { LedId.Keyboard_NumPeriodAndDelete, (5,17) }
        };

        #endregion

        #region MasterKeysS

        private static readonly Dictionary<LedId, (int row, int column)> MasterKeysS_US = new Dictionary<LedId, (int row, int column)>
        {
            { LedId.Keyboard_Escape, (0,0) },
            { LedId.Keyboard_F1, (0,1) },
            { LedId.Keyboard_F2, (0,2) },
            { LedId.Keyboard_F3, (0,3) },
            { LedId.Keyboard_F4, (0,4) },
            { LedId.Keyboard_F5, (0,6) },
            { LedId.Keyboard_F6, (0,7) },
            { LedId.Keyboard_F7, (0,8) },
            { LedId.Keyboard_F8, (0,9) },
            { LedId.Keyboard_F9, (0,11) },
            { LedId.Keyboard_F10, (0,12) },
            { LedId.Keyboard_F11, (0,13) },
            { LedId.Keyboard_F12, (0,14) },
            { LedId.Keyboard_PrintScreen, (0,15) },
            { LedId.Keyboard_ScrollLock, (0,16) },
            { LedId.Keyboard_PauseBreak, (0,17) },

            { LedId.Keyboard_GraveAccentAndTilde, (1,0) },
            { LedId.Keyboard_1, (1,1) },
            { LedId.Keyboard_2, (1,2) },
            { LedId.Keyboard_3, (1,3) },
            { LedId.Keyboard_4, (1,4) },
            { LedId.Keyboard_5, (1,5) },
            { LedId.Keyboard_6, (1,6) },
            { LedId.Keyboard_7, (1,7) },
            { LedId.Keyboard_8, (1,8) },
            { LedId.Keyboard_9, (1,9) },
            { LedId.Keyboard_0, (1,10) },
            { LedId.Keyboard_MinusAndUnderscore, (1,11) },
            { LedId.Keyboard_EqualsAndPlus, (1,12) },
            { LedId.Keyboard_Backspace, (1,14) },
            { LedId.Keyboard_Insert, (1,15) },
            { LedId.Keyboard_Home, (1,16) },
            { LedId.Keyboard_PageUp, (1,17) },

            { LedId.Keyboard_Tab, (2,0) },
            { LedId.Keyboard_Q, (2,1) },
            { LedId.Keyboard_W, (2,2) },
            { LedId.Keyboard_E, (2,3) },
            { LedId.Keyboard_R, (2,4) },
            { LedId.Keyboard_T, (2,5) },
            { LedId.Keyboard_Y, (2,6) },
            { LedId.Keyboard_U, (2,7) },
            { LedId.Keyboard_I, (2,8) },
            { LedId.Keyboard_O, (2,9) },
            { LedId.Keyboard_P, (2,10) },
            { LedId.Keyboard_BracketLeft, (2,11) },
            { LedId.Keyboard_BracketRight, (2,12) },
            { LedId.Keyboard_Backslash, (2,14) },
            { LedId.Keyboard_Delete, (2,15) },
            { LedId.Keyboard_End, (2,16) },
            { LedId.Keyboard_PageDown, (2,17) },

            { LedId.Keyboard_CapsLock, (3,0) },
            { LedId.Keyboard_A, (3,1) },
            { LedId.Keyboard_S, (3,2) },
            { LedId.Keyboard_D, (3,3) },
            { LedId.Keyboard_F, (3,4) },
            { LedId.Keyboard_G, (3,5) },
            { LedId.Keyboard_H, (3,6) },
            { LedId.Keyboard_J, (3,7) },
            { LedId.Keyboard_K, (3,8) },
            { LedId.Keyboard_L, (3,9) },
            { LedId.Keyboard_SemicolonAndColon, (3,10) },
            { LedId.Keyboard_ApostropheAndDoubleQuote, (3,11) },
            { LedId.Keyboard_Enter, (3,14) },

            { LedId.Keyboard_LeftShift, (4,0) },
            { LedId.Keyboard_Z, (4,2) },
            { LedId.Keyboard_X, (4,3) },
            { LedId.Keyboard_C, (4,4) },
            { LedId.Keyboard_V, (4,5) },
            { LedId.Keyboard_B, (4,6) },
            { LedId.Keyboard_N, (4,7) },
            { LedId.Keyboard_M, (4,8) },
            { LedId.Keyboard_CommaAndLessThan, (4,9) },
            { LedId.Keyboard_PeriodAndBiggerThan, (4,10) },
            { LedId.Keyboard_SlashAndQuestionMark, (4,11) },
            { LedId.Keyboard_RightShift, (4,14) },
            { LedId.Keyboard_ArrowUp, (4,16) },

            { LedId.Keyboard_LeftCtrl, (5,0) },
            { LedId.Keyboard_LeftGui, (5,1) },
            { LedId.Keyboard_LeftAlt, (5,2) },
            { LedId.Keyboard_Space, (5,6) },
            { LedId.Keyboard_RightAlt, (5,10) },
            { LedId.Keyboard_RightGui, (5,11) },
            { LedId.Keyboard_Application, (5,12) },
            { LedId.Keyboard_RightCtrl, (5,14) },
            { LedId.Keyboard_ArrowLeft, (5,15) },
            { LedId.Keyboard_ArrowDown, (5,16) },
            { LedId.Keyboard_ArrowRight, (5,17) }
        };

        private static readonly Dictionary<LedId, (int row, int column)> MasterKeysS_EU = new Dictionary<LedId, (int row, int column)>
        {
            { LedId.Keyboard_Escape, (0,0) },
            { LedId.Keyboard_F1, (0,1) },
            { LedId.Keyboard_F2, (0,2) },
            { LedId.Keyboard_F3, (0,3) },
            { LedId.Keyboard_F4, (0,4) },
            { LedId.Keyboard_F5, (0,6) },
            { LedId.Keyboard_F6, (0,7) },
            { LedId.Keyboard_F7, (0,8) },
            { LedId.Keyboard_F8, (0,9) },
            { LedId.Keyboard_F9, (0,11) },
            { LedId.Keyboard_F10, (0,12) },
            { LedId.Keyboard_F11, (0,13) },
            { LedId.Keyboard_F12, (0,14) },
            { LedId.Keyboard_PrintScreen, (0,15) },
            { LedId.Keyboard_ScrollLock, (0,16) },
            { LedId.Keyboard_PauseBreak, (0,17) },

            { LedId.Keyboard_GraveAccentAndTilde, (1,0) },
            { LedId.Keyboard_1, (1,1) },
            { LedId.Keyboard_2, (1,2) },
            { LedId.Keyboard_3, (1,3) },
            { LedId.Keyboard_4, (1,4) },
            { LedId.Keyboard_5, (1,5) },
            { LedId.Keyboard_6, (1,6) },
            { LedId.Keyboard_7, (1,7) },
            { LedId.Keyboard_8, (1,8) },
            { LedId.Keyboard_9, (1,9) },
            { LedId.Keyboard_0, (1,10) },
            { LedId.Keyboard_MinusAndUnderscore, (1,11) },
            { LedId.Keyboard_EqualsAndPlus, (1,12) },
            { LedId.Keyboard_Backspace, (1,14) },
            { LedId.Keyboard_Insert, (1,15) },
            { LedId.Keyboard_Home, (1,16) },
            { LedId.Keyboard_PageUp, (1,17) },

            { LedId.Keyboard_Tab, (2,0) },
            { LedId.Keyboard_Q, (2,1) },
            { LedId.Keyboard_W, (2,2) },
            { LedId.Keyboard_E, (2,3) },
            { LedId.Keyboard_R, (2,4) },
            { LedId.Keyboard_T, (2,5) },
            { LedId.Keyboard_Y, (2,6) },
            { LedId.Keyboard_U, (2,7) },
            { LedId.Keyboard_I, (2,8) },
            { LedId.Keyboard_O, (2,9) },
            { LedId.Keyboard_P, (2,10) },
            { LedId.Keyboard_BracketLeft, (2,11) },
            { LedId.Keyboard_BracketRight, (2,12) },
            { LedId.Keyboard_Enter, (2,14) },
            { LedId.Keyboard_Delete, (2,15) },
            { LedId.Keyboard_End, (2,16) },
            { LedId.Keyboard_PageDown, (2,17) },

            { LedId.Keyboard_CapsLock, (3,0) },
            { LedId.Keyboard_A, (3,1) },
            { LedId.Keyboard_S, (3,2) },
            { LedId.Keyboard_D, (3,3) },
            { LedId.Keyboard_F, (3,4) },
            { LedId.Keyboard_G, (3,5) },
            { LedId.Keyboard_H, (3,6) },
            { LedId.Keyboard_J, (3,7) },
            { LedId.Keyboard_K, (3,8) },
            { LedId.Keyboard_L, (3,9) },
            { LedId.Keyboard_SemicolonAndColon, (3,10) },
            { LedId.Keyboard_ApostropheAndDoubleQuote, (3,11) },
            { LedId.Keyboard_NonUsTilde, (3,12) },

            { LedId.Keyboard_LeftShift, (4,0) },
            { LedId.Keyboard_NonUsBackslash, (4,1) },
            { LedId.Keyboard_Z, (4,2) },
            { LedId.Keyboard_X, (4,3) },
            { LedId.Keyboard_C, (4,4) },
            { LedId.Keyboard_V, (4,5) },
            { LedId.Keyboard_B, (4,6) },
            { LedId.Keyboard_N, (4,7) },
            { LedId.Keyboard_M, (4,8) },
            { LedId.Keyboard_CommaAndLessThan, (4,9) },
            { LedId.Keyboard_PeriodAndBiggerThan, (4,10) },
            { LedId.Keyboard_SlashAndQuestionMark, (4,11) },
            { LedId.Keyboard_RightShift, (4,14) },
            { LedId.Keyboard_ArrowUp, (4,16) },

            { LedId.Keyboard_LeftCtrl, (5,0) },
            { LedId.Keyboard_LeftGui, (5,1) },
            { LedId.Keyboard_LeftAlt, (5,2) },
            { LedId.Keyboard_Space, (5,6) },
            { LedId.Keyboard_RightAlt, (5,10) },
            { LedId.Keyboard_RightGui, (5,11) },
            { LedId.Keyboard_Application, (5,12) },
            { LedId.Keyboard_RightCtrl, (5,14) },
            { LedId.Keyboard_ArrowLeft, (5,15) },
            { LedId.Keyboard_ArrowDown, (5,16) },
            { LedId.Keyboard_ArrowRight, (5,17) }
        };

        #endregion

        #region MasterKeysMK750

        private static readonly Dictionary<LedId, (int row, int column)> MasterKeysMK750_US = new Dictionary<LedId, (int row, int column)>
        {
            { LedId.Keyboard_Escape, (0,0) },
            { LedId.Keyboard_F1, (0,1) },
            { LedId.Keyboard_F2, (0,2) },
            { LedId.Keyboard_F3, (0,3) },
            { LedId.Keyboard_F4, (0,4) },
            { LedId.Keyboard_F5, (0,6) },
            { LedId.Keyboard_F6, (0,7) },
            { LedId.Keyboard_F7, (0,8) },
            { LedId.Keyboard_F8, (0,9) },
            { LedId.Keyboard_F9, (0,11) },
            { LedId.Keyboard_F10, (0,12) },
            { LedId.Keyboard_F11, (0,13) },
            { LedId.Keyboard_F12, (0,14) },
            { LedId.Keyboard_PrintScreen, (0,15) },
            { LedId.Keyboard_ScrollLock, (0,16) },
            { LedId.Keyboard_PauseBreak, (0,17) },
            { LedId.Keyboard_Programmable1, (0,18) },
            { LedId.Keyboard_Programmable2, (0,19) },
            { LedId.Keyboard_Programmable3, (0,20) },
            { LedId.Keyboard_Programmable4, (0,21) },
            { LedId.Keyboard_Custom1, (0,22) },
            { LedId.Keyboard_Custom23, (0,23) },

            { LedId.Keyboard_GraveAccentAndTilde, (1,0) },
            { LedId.Keyboard_1, (1,1) },
            { LedId.Keyboard_2, (1,2) },
            { LedId.Keyboard_3, (1,3) },
            { LedId.Keyboard_4, (1,4) },
            { LedId.Keyboard_5, (1,5) },
            { LedId.Keyboard_6, (1,6) },
            { LedId.Keyboard_7, (1,7) },
            { LedId.Keyboard_8, (1,8) },
            { LedId.Keyboard_9, (1,9) },
            { LedId.Keyboard_0, (1,10) },
            { LedId.Keyboard_MinusAndUnderscore, (1,11) },
            { LedId.Keyboard_EqualsAndPlus, (1,12) },
            { LedId.Keyboard_Backspace, (1,14) },
            { LedId.Keyboard_Insert, (1,15) },
            { LedId.Keyboard_Home, (1,16) },
            { LedId.Keyboard_PageUp, (1,17) },
            { LedId.Keyboard_NumLock, (1,18) },
            { LedId.Keyboard_NumSlash, (1,19) },
            { LedId.Keyboard_NumAsterisk, (1,20) },
            { LedId.Keyboard_NumMinus, (1,21) },
            { LedId.Keyboard_Custom2, (1,22) },
            { LedId.Keyboard_Custom24, (1,23) },

            { LedId.Keyboard_Tab, (2,0) },
            { LedId.Keyboard_Q, (2,1) },
            { LedId.Keyboard_W, (2,2) },
            { LedId.Keyboard_E, (2,3) },
            { LedId.Keyboard_R, (2,4) },
            { LedId.Keyboard_T, (2,5) },
            { LedId.Keyboard_Y, (2,6) },
            { LedId.Keyboard_U, (2,7) },
            { LedId.Keyboard_I, (2,8) },
            { LedId.Keyboard_O, (2,9) },
            { LedId.Keyboard_P, (2,10) },
            { LedId.Keyboard_BracketLeft, (2,11) },
            { LedId.Keyboard_BracketRight, (2,12) },
            { LedId.Keyboard_Backslash, (2,14) },
            { LedId.Keyboard_Delete, (2,15) },
            { LedId.Keyboard_End, (2,16) },
            { LedId.Keyboard_PageDown, (2,17) },
            { LedId.Keyboard_Num7, (2,18) },
            { LedId.Keyboard_Num8, (2,19) },
            { LedId.Keyboard_Num9, (2,20) },
            { LedId.Keyboard_NumPlus, (2,21) },
            { LedId.Keyboard_Custom3, (2,22) },
            { LedId.Keyboard_Custom25, (2,23) },

            { LedId.Keyboard_CapsLock, (3,0) },
            { LedId.Keyboard_A, (3,1) },
            { LedId.Keyboard_S, (3,2) },
            { LedId.Keyboard_D, (3,3) },
            { LedId.Keyboard_F, (3,4) },
            { LedId.Keyboard_G, (3,5) },
            { LedId.Keyboard_H, (3,6) },
            { LedId.Keyboard_J, (3,7) },
            { LedId.Keyboard_K, (3,8) },
            { LedId.Keyboard_L, (3,9) },
            { LedId.Keyboard_SemicolonAndColon, (3,10) },
            { LedId.Keyboard_ApostropheAndDoubleQuote, (3,11) },
            { LedId.Keyboard_Enter, (3,14) },
            { LedId.Keyboard_Num4, (3,18) },
            { LedId.Keyboard_Num5, (3,19) },
            { LedId.Keyboard_Num6, (3,20) },
            { LedId.Keyboard_Custom4, (3,22) },
            { LedId.Keyboard_Custom26, (3,23) },

            { LedId.Keyboard_LeftShift, (4,0) },
            { LedId.Keyboard_Z, (4,2) },
            { LedId.Keyboard_X, (4,3) },
            { LedId.Keyboard_C, (4,4) },
            { LedId.Keyboard_V, (4,5) },
            { LedId.Keyboard_B, (4,6) },
            { LedId.Keyboard_N, (4,7) },
            { LedId.Keyboard_M, (4,8) },
            { LedId.Keyboard_CommaAndLessThan, (4,9) },
            { LedId.Keyboard_PeriodAndBiggerThan, (4,10) },
            { LedId.Keyboard_SlashAndQuestionMark, (4,11) },
            { LedId.Keyboard_RightShift, (4,14) },
            { LedId.Keyboard_ArrowUp, (4,16) },
            { LedId.Keyboard_Num1, (4,18) },
            { LedId.Keyboard_Num2, (4,19) },
            { LedId.Keyboard_Num3, (4,20) },
            { LedId.Keyboard_NumEnter, (4,21) },

            { LedId.Keyboard_LeftCtrl, (5,0) },
            { LedId.Keyboard_LeftGui, (5,1) },
            { LedId.Keyboard_LeftAlt, (5,2) },
            { LedId.Keyboard_Space, (5,6) },
            { LedId.Keyboard_RightAlt, (5,10) },
            { LedId.Keyboard_RightGui, (5,11) },
            { LedId.Keyboard_Application, (5,12) },
            { LedId.Keyboard_RightCtrl, (5,14) },
            { LedId.Keyboard_ArrowLeft, (5,15) },
            { LedId.Keyboard_ArrowDown, (5,16) },
            { LedId.Keyboard_ArrowRight, (5,17) },
            { LedId.Keyboard_Num0, (5,18) },
            { LedId.Keyboard_NumPeriodAndDelete, (5,20) },

            { LedId.Keyboard_Custom5, (6,0) },
            { LedId.Keyboard_Custom6, (6,1) },
            { LedId.Keyboard_Custom7, (6,2) },
            { LedId.Keyboard_Custom8, (6,3) },
            { LedId.Keyboard_Custom9, (6,4) },
            { LedId.Keyboard_Custom10, (6,5) },
            { LedId.Keyboard_Custom11, (6,6) },
            { LedId.Keyboard_Custom12, (6,7) },
            { LedId.Keyboard_Custom13, (6,8) },
            { LedId.Keyboard_Custom14, (6,9) },
            { LedId.Keyboard_Custom15, (6,10) },
            { LedId.Keyboard_Custom16, (6,11) },
            { LedId.Keyboard_Custom17, (6,12) },
            { LedId.Keyboard_Custom18, (6,13) },
            { LedId.Keyboard_Custom19, (6,14) },
            { LedId.Keyboard_Custom20, (6,15) },
            { LedId.Keyboard_Custom21, (6,16) },
            { LedId.Keyboard_Custom22, (6,17) },
        };

        private static readonly Dictionary<LedId, (int row, int column)> MasterKeysMK750_EU = new Dictionary<LedId, (int row, int column)>
        {
            { LedId.Keyboard_Escape, (0,0) },
            { LedId.Keyboard_F1, (0,1) },
            { LedId.Keyboard_F2, (0,2) },
            { LedId.Keyboard_F3, (0,3) },
            { LedId.Keyboard_F4, (0,4) },
            { LedId.Keyboard_F5, (0,6) },
            { LedId.Keyboard_F6, (0,7) },
            { LedId.Keyboard_F7, (0,8) },
            { LedId.Keyboard_F8, (0,9) },
            { LedId.Keyboard_F9, (0,11) },
            { LedId.Keyboard_F10, (0,12) },
            { LedId.Keyboard_F11, (0,13) },
            { LedId.Keyboard_F12, (0,14) },
            { LedId.Keyboard_PrintScreen, (0,15) },
            { LedId.Keyboard_ScrollLock, (0,16) },
            { LedId.Keyboard_PauseBreak, (0,17) },
            { LedId.Keyboard_Programmable1, (0,18) },
            { LedId.Keyboard_Programmable2, (0,19) },
            { LedId.Keyboard_Programmable3, (0,20) },
            { LedId.Keyboard_Programmable4, (0,21) },
            { LedId.Keyboard_Custom1, (0,22) },
            { LedId.Keyboard_Custom23, (0,23) },

            { LedId.Keyboard_GraveAccentAndTilde, (1,0) },
            { LedId.Keyboard_1, (1,1) },
            { LedId.Keyboard_2, (1,2) },
            { LedId.Keyboard_3, (1,3) },
            { LedId.Keyboard_4, (1,4) },
            { LedId.Keyboard_5, (1,5) },
            { LedId.Keyboard_6, (1,6) },
            { LedId.Keyboard_7, (1,7) },
            { LedId.Keyboard_8, (1,8) },
            { LedId.Keyboard_9, (1,9) },
            { LedId.Keyboard_0, (1,10) },
            { LedId.Keyboard_MinusAndUnderscore, (1,11) },
            { LedId.Keyboard_EqualsAndPlus, (1,12) },
            { LedId.Keyboard_Backspace, (1,14) },
            { LedId.Keyboard_Insert, (1,15) },
            { LedId.Keyboard_Home, (1,16) },
            { LedId.Keyboard_PageUp, (1,17) },
            { LedId.Keyboard_NumLock, (1,18) },
            { LedId.Keyboard_NumSlash, (1,19) },
            { LedId.Keyboard_NumAsterisk, (1,20) },
            { LedId.Keyboard_NumMinus, (1,21) },
            { LedId.Keyboard_Custom2, (1,22) },
            { LedId.Keyboard_Custom24, (1,23) },

            { LedId.Keyboard_Tab, (2,0) },
            { LedId.Keyboard_Q, (2,1) },
            { LedId.Keyboard_W, (2,2) },
            { LedId.Keyboard_E, (2,3) },
            { LedId.Keyboard_R, (2,4) },
            { LedId.Keyboard_T, (2,5) },
            { LedId.Keyboard_Y, (2,6) },
            { LedId.Keyboard_U, (2,7) },
            { LedId.Keyboard_I, (2,8) },
            { LedId.Keyboard_O, (2,9) },
            { LedId.Keyboard_P, (2,10) },
            { LedId.Keyboard_BracketLeft, (2,11) },
            { LedId.Keyboard_BracketRight, (2,12) },
            { LedId.Keyboard_Enter, (2,14) },
            { LedId.Keyboard_Delete, (2,15) },
            { LedId.Keyboard_End, (2,16) },
            { LedId.Keyboard_PageDown, (2,17) },
            { LedId.Keyboard_Num7, (2,18) },
            { LedId.Keyboard_Num8, (2,19) },
            { LedId.Keyboard_Num9, (2,20) },
            { LedId.Keyboard_NumPlus, (2,21) },
            { LedId.Keyboard_Custom3, (2,22) },
            { LedId.Keyboard_Custom25, (2,23) },

            { LedId.Keyboard_CapsLock, (3,0) },
            { LedId.Keyboard_A, (3,1) },
            { LedId.Keyboard_S, (3,2) },
            { LedId.Keyboard_D, (3,3) },
            { LedId.Keyboard_F, (3,4) },
            { LedId.Keyboard_G, (3,5) },
            { LedId.Keyboard_H, (3,6) },
            { LedId.Keyboard_J, (3,7) },
            { LedId.Keyboard_K, (3,8) },
            { LedId.Keyboard_L, (3,9) },
            { LedId.Keyboard_SemicolonAndColon, (3,10) },
            { LedId.Keyboard_ApostropheAndDoubleQuote, (3,11) },
            { LedId.Keyboard_NonUsTilde, (3,12) },
            { LedId.Keyboard_Num4, (3,18) },
            { LedId.Keyboard_Num5, (3,19) },
            { LedId.Keyboard_Num6, (3,20) },
            { LedId.Keyboard_Custom4, (3,22) },
            { LedId.Keyboard_Custom26, (3,23) },

            { LedId.Keyboard_LeftShift, (4,0) },
            { LedId.Keyboard_NonUsBackslash, (4,1) },
            { LedId.Keyboard_Z, (4,2) },
            { LedId.Keyboard_X, (4,3) },
            { LedId.Keyboard_C, (4,4) },
            { LedId.Keyboard_V, (4,5) },
            { LedId.Keyboard_B, (4,6) },
            { LedId.Keyboard_N, (4,7) },
            { LedId.Keyboard_M, (4,8) },
            { LedId.Keyboard_CommaAndLessThan, (4,9) },
            { LedId.Keyboard_PeriodAndBiggerThan, (4,10) },
            { LedId.Keyboard_SlashAndQuestionMark, (4,11) },
            { LedId.Keyboard_RightShift, (4,14) },
            { LedId.Keyboard_ArrowUp, (4,16) },
            { LedId.Keyboard_Num1, (4,18) },
            { LedId.Keyboard_Num2, (4,19) },
            { LedId.Keyboard_Num3, (4,20) },
            { LedId.Keyboard_NumEnter, (4,21) },

            { LedId.Keyboard_LeftCtrl, (5,0) },
            { LedId.Keyboard_LeftGui, (5,1) },
            { LedId.Keyboard_LeftAlt, (5,2) },
            { LedId.Keyboard_Space, (5,6) },
            { LedId.Keyboard_RightAlt, (5,10) },
            { LedId.Keyboard_RightGui, (5,11) },
            { LedId.Keyboard_Application, (5,12) },
            { LedId.Keyboard_RightCtrl, (5,14) },
            { LedId.Keyboard_ArrowLeft, (5,15) },
            { LedId.Keyboard_ArrowDown, (5,16) },
            { LedId.Keyboard_ArrowRight, (5,17) },
            { LedId.Keyboard_Num0, (5,18) },
            { LedId.Keyboard_NumPeriodAndDelete, (5,20) },

            { LedId.Keyboard_Custom5, (6,0) },
            { LedId.Keyboard_Custom6, (6,1) },
            { LedId.Keyboard_Custom7, (6,2) },
            { LedId.Keyboard_Custom8, (6,3) },
            { LedId.Keyboard_Custom9, (6,4) },
            { LedId.Keyboard_Custom10, (6,5) },
            { LedId.Keyboard_Custom11, (6,6) },
            { LedId.Keyboard_Custom12, (6,7) },
            { LedId.Keyboard_Custom13, (6,8) },
            { LedId.Keyboard_Custom14, (6,9) },
            { LedId.Keyboard_Custom15, (6,10) },
            { LedId.Keyboard_Custom16, (6,11) },
            { LedId.Keyboard_Custom17, (6,12) },
            { LedId.Keyboard_Custom18, (6,13) },
            { LedId.Keyboard_Custom19, (6,14) },
            { LedId.Keyboard_Custom20, (6,15) },
            { LedId.Keyboard_Custom21, (6,16) },
            { LedId.Keyboard_Custom22, (6,17) }
        };

        private static readonly Dictionary<LedId, (int row, int column)> MasterKeysMK750_JP = new Dictionary<LedId, (int row, int column)>
        {
            { LedId.Keyboard_Escape, (0,0) },
            { LedId.Keyboard_F1, (0,1) },
            { LedId.Keyboard_F2, (0,2) },
            { LedId.Keyboard_F3, (0,3) },
            { LedId.Keyboard_F4, (0,4) },
            { LedId.Keyboard_F5, (0,6) },
            { LedId.Keyboard_F6, (0,7) },
            { LedId.Keyboard_F7, (0,8) },
            { LedId.Keyboard_F8, (0,9) },
            { LedId.Keyboard_F9, (0,11) },
            { LedId.Keyboard_F10, (0,12) },
            { LedId.Keyboard_F11, (0,13) },
            { LedId.Keyboard_F12, (0,14) },
            { LedId.Keyboard_PrintScreen, (0,15) },
            { LedId.Keyboard_ScrollLock, (0,16) },
            { LedId.Keyboard_PauseBreak, (0,17) },
            { LedId.Keyboard_Programmable1, (0,18) },
            { LedId.Keyboard_Programmable2, (0,19) },
            { LedId.Keyboard_Programmable3, (0,20) },
            { LedId.Keyboard_Programmable4, (0,21) },
            { LedId.Keyboard_Custom1, (0,22) },
            { LedId.Keyboard_Custom23, (0,23) },

            { LedId.Keyboard_GraveAccentAndTilde, (1,0) },
            { LedId.Keyboard_1, (1,1) },
            { LedId.Keyboard_2, (1,2) },
            { LedId.Keyboard_3, (1,3) },
            { LedId.Keyboard_4, (1,4) },
            { LedId.Keyboard_5, (1,5) },
            { LedId.Keyboard_6, (1,6) },
            { LedId.Keyboard_7, (1,7) },
            { LedId.Keyboard_8, (1,8) },
            { LedId.Keyboard_9, (1,9) },
            { LedId.Keyboard_0, (1,10) },
            { LedId.Keyboard_MinusAndUnderscore, (1,11) },
            { LedId.Keyboard_EqualsAndPlus, (1,12) },
            { LedId.Keyboard_International1, (1,13) },
            { LedId.Keyboard_Backspace, (1,14) },
            { LedId.Keyboard_Insert, (1,15) },
            { LedId.Keyboard_Home, (1,16) },
            { LedId.Keyboard_PageUp, (1,17) },
            { LedId.Keyboard_NumLock, (1,18) },
            { LedId.Keyboard_NumSlash, (1,19) },
            { LedId.Keyboard_NumAsterisk, (1,20) },
            { LedId.Keyboard_NumMinus, (1,21) },
            { LedId.Keyboard_Custom2, (1,22) },
            { LedId.Keyboard_Custom24, (1,23) },

            { LedId.Keyboard_Tab, (2,0) },
            { LedId.Keyboard_Q, (2,1) },
            { LedId.Keyboard_W, (2,2) },
            { LedId.Keyboard_E, (2,3) },
            { LedId.Keyboard_R, (2,4) },
            { LedId.Keyboard_T, (2,5) },
            { LedId.Keyboard_Y, (2,6) },
            { LedId.Keyboard_U, (2,7) },
            { LedId.Keyboard_I, (2,8) },
            { LedId.Keyboard_O, (2,9) },
            { LedId.Keyboard_P, (2,10) },
            { LedId.Keyboard_BracketLeft, (2,11) },
            { LedId.Keyboard_BracketRight, (2,12) },
            { LedId.Keyboard_Enter, (2,14) },
            { LedId.Keyboard_Delete, (2,15) },
            { LedId.Keyboard_End, (2,16) },
            { LedId.Keyboard_PageDown, (2,17) },
            { LedId.Keyboard_Num7, (2,18) },
            { LedId.Keyboard_Num8, (2,19) },
            { LedId.Keyboard_Num9, (2,20) },
            { LedId.Keyboard_NumPlus, (2,21) },
            { LedId.Keyboard_Custom3, (2,22) },
            { LedId.Keyboard_Custom25, (2,23) },

            { LedId.Keyboard_CapsLock, (3,0) },
            { LedId.Keyboard_A, (3,1) },
            { LedId.Keyboard_S, (3,2) },
            { LedId.Keyboard_D, (3,3) },
            { LedId.Keyboard_F, (3,4) },
            { LedId.Keyboard_G, (3,5) },
            { LedId.Keyboard_H, (3,6) },
            { LedId.Keyboard_J, (3,7) },
            { LedId.Keyboard_K, (3,8) },
            { LedId.Keyboard_L, (3,9) },
            { LedId.Keyboard_SemicolonAndColon, (3,10) },
            { LedId.Keyboard_ApostropheAndDoubleQuote, (3,11) },
            { LedId.Keyboard_Backslash, (3,14) },
            { LedId.Keyboard_Num4, (3,18) },
            { LedId.Keyboard_Num5, (3,19) },
            { LedId.Keyboard_Num6, (3,20) },
            { LedId.Keyboard_Custom4, (3,22) },
            { LedId.Keyboard_Custom26, (3,23) },

            { LedId.Keyboard_LeftShift, (4,0) },
            { LedId.Keyboard_Z, (4,2) },
            { LedId.Keyboard_X, (4,3) },
            { LedId.Keyboard_C, (4,4) },
            { LedId.Keyboard_V, (4,5) },
            { LedId.Keyboard_B, (4,6) },
            { LedId.Keyboard_N, (4,7) },
            { LedId.Keyboard_M, (4,8) },
            { LedId.Keyboard_CommaAndLessThan, (4,9) },
            { LedId.Keyboard_PeriodAndBiggerThan, (4,10) },
            { LedId.Keyboard_SlashAndQuestionMark, (4,11) },
            { LedId.Keyboard_International2, (4,12) },
            { LedId.Keyboard_RightShift, (4,14) },
            { LedId.Keyboard_ArrowUp, (4,16) },
            { LedId.Keyboard_Num1, (4,18) },
            { LedId.Keyboard_Num2, (4,19) },
            { LedId.Keyboard_Num3, (4,20) },
            { LedId.Keyboard_NumEnter, (4,21) },

            { LedId.Keyboard_LeftCtrl, (5,0) },
            { LedId.Keyboard_LeftGui, (5,1) },
            { LedId.Keyboard_LeftAlt, (5,2) },
            { LedId.Keyboard_International3, (5,4) },
            { LedId.Keyboard_Space, (5,6) },
            { LedId.Keyboard_International4, (5,8) },
            { LedId.Keyboard_International5, (5,9) },
            { LedId.Keyboard_RightAlt, (5,10) },
            { LedId.Keyboard_RightGui, (5,11) },
            { LedId.Keyboard_Application, (5,12) },
            { LedId.Keyboard_RightCtrl, (5,14) },
            { LedId.Keyboard_ArrowLeft, (5,15) },
            { LedId.Keyboard_ArrowDown, (5,16) },
            { LedId.Keyboard_ArrowRight, (5,17) },
            { LedId.Keyboard_Num0, (5,18) },
            { LedId.Keyboard_NumPeriodAndDelete, (5,20) },

            { LedId.Keyboard_Custom5, (6,0) },
            { LedId.Keyboard_Custom6, (6,1) },
            { LedId.Keyboard_Custom7, (6,2) },
            { LedId.Keyboard_Custom8, (6,3) },
            { LedId.Keyboard_Custom9, (6,4) },
            { LedId.Keyboard_Custom10, (6,5) },
            { LedId.Keyboard_Custom11, (6,6) },
            { LedId.Keyboard_Custom12, (6,7) },
            { LedId.Keyboard_Custom13, (6,8) },
            { LedId.Keyboard_Custom14, (6,9) },
            { LedId.Keyboard_Custom15, (6,10) },
            { LedId.Keyboard_Custom16, (6,11) },
            { LedId.Keyboard_Custom17, (6,12) },
            { LedId.Keyboard_Custom18, (6,13) },
            { LedId.Keyboard_Custom19, (6,14) },
            { LedId.Keyboard_Custom20, (6,15) },
            { LedId.Keyboard_Custom21, (6,16) },
            { LedId.Keyboard_Custom22, (6,17) },
        };

        #endregion

        #region CKxxx

        private static readonly Dictionary<LedId, (int row, int column)> CKxxx_US = new Dictionary<LedId, (int row, int column)>
        {
            { LedId.Keyboard_Escape, (0,0) },
            { LedId.Keyboard_F1, (0,1) },
            { LedId.Keyboard_F2, (0,2) },
            { LedId.Keyboard_F3, (0,3) },
            { LedId.Keyboard_F4, (0,4) },
            { LedId.Keyboard_F5, (0,6) },
            { LedId.Keyboard_F6, (0,7) },
            { LedId.Keyboard_F7, (0,8) },
            { LedId.Keyboard_F8, (0,9) },
            { LedId.Keyboard_F9, (0,11) },
            { LedId.Keyboard_F10, (0,12) },
            { LedId.Keyboard_F11, (0,13) },
            { LedId.Keyboard_F12, (0,14) },
            { LedId.Keyboard_PrintScreen, (0,15) },
            { LedId.Keyboard_ScrollLock, (0,16) },
            { LedId.Keyboard_PauseBreak, (0,17) },

            { LedId.Keyboard_GraveAccentAndTilde, (1,0) },
            { LedId.Keyboard_1, (1,1) },
            { LedId.Keyboard_2, (1,2) },
            { LedId.Keyboard_3, (1,3) },
            { LedId.Keyboard_4, (1,4) },
            { LedId.Keyboard_5, (1,5) },
            { LedId.Keyboard_6, (1,6) },
            { LedId.Keyboard_7, (1,7) },
            { LedId.Keyboard_8, (1,8) },
            { LedId.Keyboard_9, (1,9) },
            { LedId.Keyboard_0, (1,10) },
            { LedId.Keyboard_MinusAndUnderscore, (1,11) },
            { LedId.Keyboard_EqualsAndPlus, (1,12) },
            { LedId.Keyboard_Backspace, (1,14) },
            { LedId.Keyboard_Insert, (1,15) },
            { LedId.Keyboard_Home, (1,16) },
            { LedId.Keyboard_PageUp, (1,17) },
            { LedId.Keyboard_NumLock, (1,18) },
            { LedId.Keyboard_NumSlash, (1,19) },
            { LedId.Keyboard_NumAsterisk, (1,20) },
            { LedId.Keyboard_NumMinus, (1,21) },

            { LedId.Keyboard_Tab, (2,0) },
            { LedId.Keyboard_Q, (2,1) },
            { LedId.Keyboard_W, (2,2) },
            { LedId.Keyboard_E, (2,3) },
            { LedId.Keyboard_R, (2,4) },
            { LedId.Keyboard_T, (2,5) },
            { LedId.Keyboard_Y, (2,6) },
            { LedId.Keyboard_U, (2,7) },
            { LedId.Keyboard_I, (2,8) },
            { LedId.Keyboard_O, (2,9) },
            { LedId.Keyboard_P, (2,10) },
            { LedId.Keyboard_BracketLeft, (2,11) },
            { LedId.Keyboard_BracketRight, (2,12) },
            { LedId.Keyboard_Backslash, (2,14) },
            { LedId.Keyboard_Delete, (2,15) },
            { LedId.Keyboard_End, (2,16) },
            { LedId.Keyboard_PageDown, (2,17) },
            { LedId.Keyboard_Num7, (2,18) },
            { LedId.Keyboard_Num8, (2,19) },
            { LedId.Keyboard_Num9, (2,20) },
            { LedId.Keyboard_NumPlus, (2,21) },

            { LedId.Keyboard_CapsLock, (3,0) },
            { LedId.Keyboard_A, (3,1) },
            { LedId.Keyboard_S, (3,2) },
            { LedId.Keyboard_D, (3,3) },
            { LedId.Keyboard_F, (3,4) },
            { LedId.Keyboard_G, (3,5) },
            { LedId.Keyboard_H, (3,6) },
            { LedId.Keyboard_J, (3,7) },
            { LedId.Keyboard_K, (3,8) },
            { LedId.Keyboard_L, (3,9) },
            { LedId.Keyboard_SemicolonAndColon, (3,10) },
            { LedId.Keyboard_ApostropheAndDoubleQuote, (3,11) },
            { LedId.Keyboard_Enter, (3,14) },
            { LedId.Keyboard_Num4, (3,18) },
            { LedId.Keyboard_Num5, (3,19) },
            { LedId.Keyboard_Num6, (3,20) },

            { LedId.Keyboard_LeftShift, (4,0) },
            { LedId.Keyboard_Z, (4,2) },
            { LedId.Keyboard_X, (4,3) },
            { LedId.Keyboard_C, (4,4) },
            { LedId.Keyboard_V, (4,5) },
            { LedId.Keyboard_B, (4,6) },
            { LedId.Keyboard_N, (4,7) },
            { LedId.Keyboard_M, (4,8) },
            { LedId.Keyboard_CommaAndLessThan, (4,9) },
            { LedId.Keyboard_PeriodAndBiggerThan, (4,10) },
            { LedId.Keyboard_SlashAndQuestionMark, (4,11) },
            { LedId.Keyboard_RightShift, (4,14) },
            { LedId.Keyboard_ArrowUp, (4,16) },
            { LedId.Keyboard_Num1, (4,18) },
            { LedId.Keyboard_Num2, (4,19) },
            { LedId.Keyboard_Num3, (4,20) },
            { LedId.Keyboard_NumEnter, (4,21) },

            { LedId.Keyboard_LeftCtrl, (5,0) },
            { LedId.Keyboard_LeftGui, (5,1) },
            { LedId.Keyboard_LeftAlt, (5,2) },
            { LedId.Keyboard_Space, (5,6) },
            { LedId.Keyboard_RightAlt, (5,10) },
            { LedId.Keyboard_RightGui, (5,11) },
            { LedId.Keyboard_Application, (5,12) },
            { LedId.Keyboard_RightCtrl, (5,14) },
            { LedId.Keyboard_ArrowLeft, (5,15) },
            { LedId.Keyboard_ArrowDown, (5,16) },
            { LedId.Keyboard_ArrowRight, (5,17) },
            { LedId.Keyboard_Num0, (5,18) },
            { LedId.Keyboard_NumPeriodAndDelete, (5,20) }
        };

        private static readonly Dictionary<LedId, (int row, int column)> CKxxx_EU = new Dictionary<LedId, (int row, int column)>
        {
            { LedId.Keyboard_Escape, (0,0) },
            { LedId.Keyboard_F1, (0,1) },
            { LedId.Keyboard_F2, (0,2) },
            { LedId.Keyboard_F3, (0,3) },
            { LedId.Keyboard_F4, (0,4) },
            { LedId.Keyboard_F5, (0,6) },
            { LedId.Keyboard_F6, (0,7) },
            { LedId.Keyboard_F7, (0,8) },
            { LedId.Keyboard_F8, (0,9) },
            { LedId.Keyboard_F9, (0,11) },
            { LedId.Keyboard_F10, (0,12) },
            { LedId.Keyboard_F11, (0,13) },
            { LedId.Keyboard_F12, (0,14) },
            { LedId.Keyboard_PrintScreen, (0,15) },
            { LedId.Keyboard_ScrollLock, (0,16) },
            { LedId.Keyboard_PauseBreak, (0,17) },

            { LedId.Keyboard_GraveAccentAndTilde, (1,0) },
            { LedId.Keyboard_1, (1,1) },
            { LedId.Keyboard_2, (1,2) },
            { LedId.Keyboard_3, (1,3) },
            { LedId.Keyboard_4, (1,4) },
            { LedId.Keyboard_5, (1,5) },
            { LedId.Keyboard_6, (1,6) },
            { LedId.Keyboard_7, (1,7) },
            { LedId.Keyboard_8, (1,8) },
            { LedId.Keyboard_9, (1,9) },
            { LedId.Keyboard_0, (1,10) },
            { LedId.Keyboard_MinusAndUnderscore, (1,11) },
            { LedId.Keyboard_EqualsAndPlus, (1,12) },
            { LedId.Keyboard_Backspace, (1,14) },
            { LedId.Keyboard_Insert, (1,15) },
            { LedId.Keyboard_Home, (1,16) },
            { LedId.Keyboard_PageUp, (1,17) },
            { LedId.Keyboard_NumLock, (1,18) },
            { LedId.Keyboard_NumSlash, (1,19) },
            { LedId.Keyboard_NumAsterisk, (1,20) },
            { LedId.Keyboard_NumMinus, (1,21) },

            { LedId.Keyboard_Tab, (2,0) },
            { LedId.Keyboard_Q, (2,1) },
            { LedId.Keyboard_W, (2,2) },
            { LedId.Keyboard_E, (2,3) },
            { LedId.Keyboard_R, (2,4) },
            { LedId.Keyboard_T, (2,5) },
            { LedId.Keyboard_Y, (2,6) },
            { LedId.Keyboard_U, (2,7) },
            { LedId.Keyboard_I, (2,8) },
            { LedId.Keyboard_O, (2,9) },
            { LedId.Keyboard_P, (2,10) },
            { LedId.Keyboard_BracketLeft, (2,11) },
            { LedId.Keyboard_BracketRight, (2,12) },
            { LedId.Keyboard_Enter, (2,14) },
            { LedId.Keyboard_Delete, (2,15) },
            { LedId.Keyboard_End, (2,16) },
            { LedId.Keyboard_PageDown, (2,17) },
            { LedId.Keyboard_Num7, (2,18) },
            { LedId.Keyboard_Num8, (2,19) },
            { LedId.Keyboard_Num9, (2,20) },
            { LedId.Keyboard_NumPlus, (2,21) },

            { LedId.Keyboard_CapsLock, (3,0) },
            { LedId.Keyboard_A, (3,1) },
            { LedId.Keyboard_S, (3,2) },
            { LedId.Keyboard_D, (3,3) },
            { LedId.Keyboard_F, (3,4) },
            { LedId.Keyboard_G, (3,5) },
            { LedId.Keyboard_H, (3,6) },
            { LedId.Keyboard_J, (3,7) },
            { LedId.Keyboard_K, (3,8) },
            { LedId.Keyboard_L, (3,9) },
            { LedId.Keyboard_SemicolonAndColon, (3,10) },
            { LedId.Keyboard_ApostropheAndDoubleQuote, (3,11) },
            { LedId.Keyboard_NonUsTilde, (3,12) },
            { LedId.Keyboard_Num4, (3,18) },
            { LedId.Keyboard_Num5, (3,19) },
            { LedId.Keyboard_Num6, (3,20) },

            { LedId.Keyboard_LeftShift, (4,0) },
            { LedId.Keyboard_NonUsBackslash, (4,1) },
            { LedId.Keyboard_Z, (4,2) },
            { LedId.Keyboard_X, (4,3) },
            { LedId.Keyboard_C, (4,4) },
            { LedId.Keyboard_V, (4,5) },
            { LedId.Keyboard_B, (4,6) },
            { LedId.Keyboard_N, (4,7) },
            { LedId.Keyboard_M, (4,8) },
            { LedId.Keyboard_CommaAndLessThan, (4,9) },
            { LedId.Keyboard_PeriodAndBiggerThan, (4,10) },
            { LedId.Keyboard_SlashAndQuestionMark, (4,11) },
            { LedId.Keyboard_RightShift, (4,14) },
            { LedId.Keyboard_ArrowUp, (4,16) },
            { LedId.Keyboard_Num1, (4,18) },
            { LedId.Keyboard_Num2, (4,19) },
            { LedId.Keyboard_Num3, (4,20) },
            { LedId.Keyboard_NumEnter, (4,21) },

            { LedId.Keyboard_LeftCtrl, (5,0) },
            { LedId.Keyboard_LeftGui, (5,1) },
            { LedId.Keyboard_LeftAlt, (5,2) },
            { LedId.Keyboard_Space, (5,6) },
            { LedId.Keyboard_RightAlt, (5,10) },
            { LedId.Keyboard_RightGui, (5,11) },
            { LedId.Keyboard_Application, (5,12) },
            { LedId.Keyboard_RightCtrl, (5,14) },
            { LedId.Keyboard_ArrowLeft, (5,15) },
            { LedId.Keyboard_ArrowDown, (5,16) },
            { LedId.Keyboard_ArrowRight, (5,17) },
            { LedId.Keyboard_Num0, (5,18) },
            { LedId.Keyboard_NumPeriodAndDelete, (5,20) }
        };

        private static readonly Dictionary<LedId, (int row, int column)> CKxxx_JP = new Dictionary<LedId, (int row, int column)>
        {
            { LedId.Keyboard_Escape, (0,0) },
            { LedId.Keyboard_F1, (0,1) },
            { LedId.Keyboard_F2, (0,2) },
            { LedId.Keyboard_F3, (0,3) },
            { LedId.Keyboard_F4, (0,4) },
            { LedId.Keyboard_F5, (0,6) },
            { LedId.Keyboard_F6, (0,7) },
            { LedId.Keyboard_F7, (0,8) },
            { LedId.Keyboard_F8, (0,9) },
            { LedId.Keyboard_F9, (0,11) },
            { LedId.Keyboard_F10, (0,12) },
            { LedId.Keyboard_F11, (0,13) },
            { LedId.Keyboard_F12, (0,14) },
            { LedId.Keyboard_PrintScreen, (0,15) },
            { LedId.Keyboard_ScrollLock, (0,16) },
            { LedId.Keyboard_PauseBreak, (0,17) },

            { LedId.Keyboard_GraveAccentAndTilde, (1,0) },
            { LedId.Keyboard_1, (1,1) },
            { LedId.Keyboard_2, (1,2) },
            { LedId.Keyboard_3, (1,3) },
            { LedId.Keyboard_4, (1,4) },
            { LedId.Keyboard_5, (1,5) },
            { LedId.Keyboard_6, (1,6) },
            { LedId.Keyboard_7, (1,7) },
            { LedId.Keyboard_8, (1,8) },
            { LedId.Keyboard_9, (1,9) },
            { LedId.Keyboard_0, (1,10) },
            { LedId.Keyboard_MinusAndUnderscore, (1,11) },
            { LedId.Keyboard_EqualsAndPlus, (1,12) },
            { LedId.Keyboard_International1, (1,13) },
            { LedId.Keyboard_Backspace, (1,14) },
            { LedId.Keyboard_Insert, (1,15) },
            { LedId.Keyboard_Home, (1,16) },
            { LedId.Keyboard_PageUp, (1,17) },
            { LedId.Keyboard_NumLock, (1,18) },
            { LedId.Keyboard_NumSlash, (1,19) },
            { LedId.Keyboard_NumAsterisk, (1,20) },
            { LedId.Keyboard_NumMinus, (1,21) },

            { LedId.Keyboard_Tab, (2,0) },
            { LedId.Keyboard_Q, (2,1) },
            { LedId.Keyboard_W, (2,2) },
            { LedId.Keyboard_E, (2,3) },
            { LedId.Keyboard_R, (2,4) },
            { LedId.Keyboard_T, (2,5) },
            { LedId.Keyboard_Y, (2,6) },
            { LedId.Keyboard_U, (2,7) },
            { LedId.Keyboard_I, (2,8) },
            { LedId.Keyboard_O, (2,9) },
            { LedId.Keyboard_P, (2,10) },
            { LedId.Keyboard_BracketLeft, (2,11) },
            { LedId.Keyboard_BracketRight, (2,12) },
            { LedId.Keyboard_Enter, (2,14) },
            { LedId.Keyboard_Delete, (2,15) },
            { LedId.Keyboard_End, (2,16) },
            { LedId.Keyboard_PageDown, (2,17) },
            { LedId.Keyboard_Num7, (2,18) },
            { LedId.Keyboard_Num8, (2,19) },
            { LedId.Keyboard_Num9, (2,20) },
            { LedId.Keyboard_NumPlus, (2,21) },

            { LedId.Keyboard_CapsLock, (3,0) },
            { LedId.Keyboard_A, (3,1) },
            { LedId.Keyboard_S, (3,2) },
            { LedId.Keyboard_D, (3,3) },
            { LedId.Keyboard_F, (3,4) },
            { LedId.Keyboard_G, (3,5) },
            { LedId.Keyboard_H, (3,6) },
            { LedId.Keyboard_J, (3,7) },
            { LedId.Keyboard_K, (3,8) },
            { LedId.Keyboard_L, (3,9) },
            { LedId.Keyboard_SemicolonAndColon, (3,10) },
            { LedId.Keyboard_ApostropheAndDoubleQuote, (3,11) },
            { LedId.Keyboard_Backslash, (3,14) },
            { LedId.Keyboard_Num4, (3,18) },
            { LedId.Keyboard_Num5, (3,19) },
            { LedId.Keyboard_Num6, (3,20) },

            { LedId.Keyboard_LeftShift, (4,0) },
            { LedId.Keyboard_Z, (4,2) },
            { LedId.Keyboard_X, (4,3) },
            { LedId.Keyboard_C, (4,4) },
            { LedId.Keyboard_V, (4,5) },
            { LedId.Keyboard_B, (4,6) },
            { LedId.Keyboard_N, (4,7) },
            { LedId.Keyboard_M, (4,8) },
            { LedId.Keyboard_CommaAndLessThan, (4,9) },
            { LedId.Keyboard_PeriodAndBiggerThan, (4,10) },
            { LedId.Keyboard_SlashAndQuestionMark, (4,11) },
            { LedId.Keyboard_International2, (4,12) },
            { LedId.Keyboard_RightShift, (4,14) },
            { LedId.Keyboard_ArrowUp, (4,16) },
            { LedId.Keyboard_Num1, (4,18) },
            { LedId.Keyboard_Num2, (4,19) },
            { LedId.Keyboard_Num3, (4,20) },
            { LedId.Keyboard_NumEnter, (4,21) },

            { LedId.Keyboard_LeftCtrl, (5,0) },
            { LedId.Keyboard_LeftGui, (5,1) },
            { LedId.Keyboard_LeftAlt, (5,2) },
            { LedId.Keyboard_International3, (5,4) },
            { LedId.Keyboard_Space, (5,6) },
            { LedId.Keyboard_International4, (5,8) },
            { LedId.Keyboard_International5, (5,9) },
            { LedId.Keyboard_RightAlt, (5,10) },
            { LedId.Keyboard_RightGui, (5,11) },
            { LedId.Keyboard_Application, (5,12) },
            { LedId.Keyboard_RightCtrl, (5,14) },
            { LedId.Keyboard_ArrowLeft, (5,15) },
            { LedId.Keyboard_ArrowDown, (5,16) },
            { LedId.Keyboard_ArrowRight, (5,17) },
            { LedId.Keyboard_Num0, (5,18) },
            { LedId.Keyboard_NumPeriodAndDelete, (5,20) }
        };

        #endregion

        /// <summary>
        /// Contains all the hardware-id mappings for CoolerMaster devices.
        /// </summary>
        public static readonly Dictionary<CoolerMasterDevicesIndexes, Dictionary<CoolerMasterPhysicalKeyboardLayout, Dictionary<LedId, (int row, int column)>>> Mapping =
            new Dictionary<CoolerMasterDevicesIndexes, Dictionary<CoolerMasterPhysicalKeyboardLayout, Dictionary<LedId, (int row, int column)>>>
            {
                { CoolerMasterDevicesIndexes.MasterKeys_L, new Dictionary<CoolerMasterPhysicalKeyboardLayout, Dictionary<LedId, (int row, int column)>>
                  {
                    { CoolerMasterPhysicalKeyboardLayout.US, MasterKeysL_US },
                    { CoolerMasterPhysicalKeyboardLayout.EU, MasterKeysL_EU }
                  }
                },

                { CoolerMasterDevicesIndexes.MasterKeys_M, new Dictionary<CoolerMasterPhysicalKeyboardLayout, Dictionary<LedId, (int row, int column)>>
                  {
                    { CoolerMasterPhysicalKeyboardLayout.US, MasterKeysM_US },
                    { CoolerMasterPhysicalKeyboardLayout.EU, MasterKeysM_EU }
                  }
                },

                { CoolerMasterDevicesIndexes.MasterKeys_S, new Dictionary<CoolerMasterPhysicalKeyboardLayout, Dictionary<LedId, (int row, int column)>>
                  {
                    { CoolerMasterPhysicalKeyboardLayout.US, MasterKeysS_US },
                    { CoolerMasterPhysicalKeyboardLayout.EU, MasterKeysS_EU }
                  }
                },

                { CoolerMasterDevicesIndexes.MasterKeys_L_White, new Dictionary<CoolerMasterPhysicalKeyboardLayout, Dictionary<LedId, (int row, int column)>>
                  {
                    { CoolerMasterPhysicalKeyboardLayout.US, MasterKeysL_US },
                    { CoolerMasterPhysicalKeyboardLayout.EU, MasterKeysL_EU }
                  }
                },

                { CoolerMasterDevicesIndexes.MasterKeys_M_White, new Dictionary<CoolerMasterPhysicalKeyboardLayout, Dictionary<LedId, (int row, int column)>>
                  {
                    { CoolerMasterPhysicalKeyboardLayout.US, MasterKeysM_US },
                    { CoolerMasterPhysicalKeyboardLayout.EU, MasterKeysM_EU }
                  }
                },

                { CoolerMasterDevicesIndexes.MasterKeys_S_White, new Dictionary<CoolerMasterPhysicalKeyboardLayout, Dictionary<LedId, (int row, int column)>>
                  {
                    { CoolerMasterPhysicalKeyboardLayout.US, MasterKeysS_US },
                    { CoolerMasterPhysicalKeyboardLayout.EU, MasterKeysS_EU }
                  }
                },

                { CoolerMasterDevicesIndexes.MasterKeys_MK750, new Dictionary<CoolerMasterPhysicalKeyboardLayout, Dictionary<LedId, (int row, int column)>>
                  {
                    { CoolerMasterPhysicalKeyboardLayout.US, MasterKeysMK750_US},
                    { CoolerMasterPhysicalKeyboardLayout.EU, MasterKeysMK750_EU },
                    { CoolerMasterPhysicalKeyboardLayout.JP, MasterKeysMK750_JP }
                  }
                },

                { CoolerMasterDevicesIndexes.CK372, new Dictionary<CoolerMasterPhysicalKeyboardLayout, Dictionary<LedId, (int row, int column)>>
                  {
                      { CoolerMasterPhysicalKeyboardLayout.US, CKxxx_US},
                      { CoolerMasterPhysicalKeyboardLayout.EU, CKxxx_EU },
                      { CoolerMasterPhysicalKeyboardLayout.JP, CKxxx_JP }
                  }
                },

                { CoolerMasterDevicesIndexes.CK530, new Dictionary<CoolerMasterPhysicalKeyboardLayout, Dictionary<LedId, (int row, int column)>>
                  {
                      { CoolerMasterPhysicalKeyboardLayout.US, CKxxx_US},
                      { CoolerMasterPhysicalKeyboardLayout.EU, CKxxx_EU },
                      { CoolerMasterPhysicalKeyboardLayout.JP, CKxxx_JP }
                  }
                },
                
                { CoolerMasterDevicesIndexes.CK550, new Dictionary<CoolerMasterPhysicalKeyboardLayout, Dictionary<LedId, (int row, int column)>>
                  {
                      { CoolerMasterPhysicalKeyboardLayout.US, CKxxx_US},
                      { CoolerMasterPhysicalKeyboardLayout.EU, CKxxx_EU },
                      { CoolerMasterPhysicalKeyboardLayout.JP, CKxxx_JP }
                  }
                },

                { CoolerMasterDevicesIndexes.CK551, new Dictionary<CoolerMasterPhysicalKeyboardLayout, Dictionary<LedId, (int row, int column)>>
                  {
                      { CoolerMasterPhysicalKeyboardLayout.US, CKxxx_US},
                      { CoolerMasterPhysicalKeyboardLayout.EU, CKxxx_EU },
                      { CoolerMasterPhysicalKeyboardLayout.JP, CKxxx_JP }
                  }
                },
            };

        #endregion
    }
}
