using System.Collections.Generic;
using RGB.NET.Core;

namespace RGB.NET.Devices.Novation
{
    internal static class LaunchpadIdMapping
    {
        internal static readonly Dictionary<LedId, NovationLedId> DEFAULT = new Dictionary<LedId, NovationLedId>
        {
            { LedId.Invalid, NovationLedId.Invalid },

            { LedId.LedMatrix1, NovationLedId.Grid1 },
            { LedId.LedMatrix2, NovationLedId.Grid2 },
            { LedId.LedMatrix3, NovationLedId.Grid3 },
            { LedId.LedMatrix4, NovationLedId.Grid4 },
            { LedId.LedMatrix5, NovationLedId.Grid5 },
            { LedId.LedMatrix6, NovationLedId.Grid6 },
            { LedId.LedMatrix7, NovationLedId.Grid7 },
            { LedId.LedMatrix8, NovationLedId.Grid8 },
            { LedId.LedMatrix9, NovationLedId.Grid9 },
            { LedId.LedMatrix10, NovationLedId.Grid10 },
            { LedId.LedMatrix11, NovationLedId.Grid11 },
            { LedId.LedMatrix12, NovationLedId.Grid12 },
            { LedId.LedMatrix13, NovationLedId.Grid13 },
            { LedId.LedMatrix14, NovationLedId.Grid14 },
            { LedId.LedMatrix15, NovationLedId.Grid15 },
            { LedId.LedMatrix16, NovationLedId.Grid16 },
            { LedId.LedMatrix17, NovationLedId.Grid17 },
            { LedId.LedMatrix18, NovationLedId.Grid18 },
            { LedId.LedMatrix19, NovationLedId.Grid19 },
            { LedId.LedMatrix20, NovationLedId.Grid20 },
            { LedId.LedMatrix21, NovationLedId.Grid21 },
            { LedId.LedMatrix22, NovationLedId.Grid22 },
            { LedId.LedMatrix23, NovationLedId.Grid23 },
            { LedId.LedMatrix24, NovationLedId.Grid24 },
            { LedId.LedMatrix25, NovationLedId.Grid25 },
            { LedId.LedMatrix26, NovationLedId.Grid26 },
            { LedId.LedMatrix27, NovationLedId.Grid27 },
            { LedId.LedMatrix28, NovationLedId.Grid28 },
            { LedId.LedMatrix29, NovationLedId.Grid29 },
            { LedId.LedMatrix30, NovationLedId.Grid30 },
            { LedId.LedMatrix31, NovationLedId.Grid31 },
            { LedId.LedMatrix32, NovationLedId.Grid32 },
            { LedId.LedMatrix33, NovationLedId.Grid33 },
            { LedId.LedMatrix34, NovationLedId.Grid34 },
            { LedId.LedMatrix35, NovationLedId.Grid35 },
            { LedId.LedMatrix36, NovationLedId.Grid36 },
            { LedId.LedMatrix37, NovationLedId.Grid37 },
            { LedId.LedMatrix38, NovationLedId.Grid38 },
            { LedId.LedMatrix39, NovationLedId.Grid39 },
            { LedId.LedMatrix40, NovationLedId.Grid40 },
            { LedId.LedMatrix41, NovationLedId.Grid41 },
            { LedId.LedMatrix42, NovationLedId.Grid42 },
            { LedId.LedMatrix43, NovationLedId.Grid43 },
            { LedId.LedMatrix44, NovationLedId.Grid44 },
            { LedId.LedMatrix45, NovationLedId.Grid45 },
            { LedId.LedMatrix46, NovationLedId.Grid46 },
            { LedId.LedMatrix47, NovationLedId.Grid47 },
            { LedId.LedMatrix48, NovationLedId.Grid48 },
            { LedId.LedMatrix49, NovationLedId.Grid49 },
            { LedId.LedMatrix50, NovationLedId.Grid50 },
            { LedId.LedMatrix51, NovationLedId.Grid51 },
            { LedId.LedMatrix52, NovationLedId.Grid52 },
            { LedId.LedMatrix53, NovationLedId.Grid53 },
            { LedId.LedMatrix54, NovationLedId.Grid54 },
            { LedId.LedMatrix55, NovationLedId.Grid55 },
            { LedId.LedMatrix56, NovationLedId.Grid56 },
            { LedId.LedMatrix57, NovationLedId.Grid57 },
            { LedId.LedMatrix58, NovationLedId.Grid58 },
            { LedId.LedMatrix59, NovationLedId.Grid59 },
            { LedId.LedMatrix60, NovationLedId.Grid60 },
            { LedId.LedMatrix61, NovationLedId.Grid61 },
            { LedId.LedMatrix62, NovationLedId.Grid62 },
            { LedId.LedMatrix63, NovationLedId.Grid63 },
            { LedId.LedMatrix64, NovationLedId.Grid64 },

            { LedId.Custom1, NovationLedId.Up },
            { LedId.Custom2, NovationLedId.Down },
            { LedId.Custom3, NovationLedId.Left },
            { LedId.Custom4, NovationLedId.Right },
            { LedId.Custom5, NovationLedId.Session },
            { LedId.Custom6, NovationLedId.User1 },
            { LedId.Custom7, NovationLedId.User2 },
            { LedId.Custom8, NovationLedId.Mix },

            { LedId.Custom9, NovationLedId.Scene1 },
            { LedId.Custom10, NovationLedId.Scene2 },
            { LedId.Custom11, NovationLedId.Scene3 },
            { LedId.Custom12, NovationLedId.Scene4 },
            { LedId.Custom13, NovationLedId.Scene5 },
            { LedId.Custom14, NovationLedId.Scene6 },
            { LedId.Custom15, NovationLedId.Scene7 },
            { LedId.Custom16, NovationLedId.Scene8 },
        };
    }
}
