using System.Runtime.InteropServices;

namespace RGB.NET.Devices.Logitech.HID;

[StructLayout(LayoutKind.Sequential, Pack = 0, Size = 64)]
internal struct FapResponse
{
    public byte Command;
    public byte DeviceIndex;
    public byte FeatureIndex;
    public byte FeatureCommand;
    public byte Data00;
    public byte Data01;
    public byte Data02;
    public byte Data03;
    public byte Data04;
    public byte Data05;
    public byte Data06;
    public byte Data07;
    public byte Data08;
    public byte Data09;
    public byte Data10;
    public byte Data11;
    public byte Data12;
    public byte Data13;
    public byte Data14;
    public byte Data15;
    public byte Data16;
    public byte Data17;
    public byte Data18;
    public byte Data19;
    public byte Data20;
    public byte Data21;
    public byte Data22;
    public byte Data23;
    public byte Data24;
    public byte Data25;
    public byte Data26;
    public byte Data27;
    public byte Data28;
    public byte Data29;
    public byte Data30;
    public byte Data31;
    public byte Data32;
    public byte Data33;
    public byte Data34;
    public byte Data35;
    public byte Data36;
    public byte Data37;
    public byte Data38;
    public byte Data39;
    public byte Data40;
    public byte Data41;
    public byte Data42;
    public byte Data43;
    public byte Data44;
    public byte Data45;
    public byte Data46;
    public byte Data47;
    public byte Data48;
    public byte Data49;
    public byte Data50;
    public byte Data51;
    public byte Data52;
    public byte Data53;
    public byte Data54;
    public byte Data55;
    public byte Data56;
    public byte Data57;
    public byte Data58;
    public byte Data59;
}