using System.Collections.Generic;
using Windows.System;
using RGB.NET.Core;

namespace RGB.NET.Devices.DynamicLighting;

internal static class LedMappings
{
    public static Dictionary<VirtualKey, LedId> KeyboardMapping = new()
    {
        [VirtualKey.Back] = LedId.Keyboard_Backspace,
        [VirtualKey.Tab] = LedId.Keyboard_Tab,
        [VirtualKey.Enter] = LedId.Keyboard_Enter,
        [VirtualKey.Pause] = LedId.Keyboard_PauseBreak,
        [VirtualKey.CapitalLock] = LedId.Keyboard_CapsLock,
        [VirtualKey.Escape] = LedId.Keyboard_Escape,
        [VirtualKey.Space] = LedId.Keyboard_Space,
        [VirtualKey.PageUp] = LedId.Keyboard_PageUp,
        [VirtualKey.PageDown] = LedId.Keyboard_PageDown,
        [VirtualKey.End] = LedId.Keyboard_End,
        [VirtualKey.Home] = LedId.Keyboard_Home,
        [VirtualKey.Left] = LedId.Keyboard_ArrowLeft,
        [VirtualKey.Up] = LedId.Keyboard_ArrowUp,
        [VirtualKey.Right] = LedId.Keyboard_ArrowRight,
        [VirtualKey.Down] = LedId.Keyboard_ArrowDown,
        [VirtualKey.Print] = LedId.Keyboard_PrintScreen,
        [VirtualKey.Insert] = LedId.Keyboard_Insert,
        [VirtualKey.Delete] = LedId.Keyboard_Delete,
        [VirtualKey.Number0] = LedId.Keyboard_0,
        [VirtualKey.Number1] = LedId.Keyboard_1,
        [VirtualKey.Number2] = LedId.Keyboard_2,
        [VirtualKey.Number3] = LedId.Keyboard_3,
        [VirtualKey.Number4] = LedId.Keyboard_4,
        [VirtualKey.Number5] = LedId.Keyboard_5,
        [VirtualKey.Number6] = LedId.Keyboard_6,
        [VirtualKey.Number7] = LedId.Keyboard_7,
        [VirtualKey.Number8] = LedId.Keyboard_8,
        [VirtualKey.Number9] = LedId.Keyboard_9,
        [VirtualKey.A] = LedId.Keyboard_A,
        [VirtualKey.B] = LedId.Keyboard_B,
        [VirtualKey.C] = LedId.Keyboard_C,
        [VirtualKey.D] = LedId.Keyboard_D,
        [VirtualKey.E] = LedId.Keyboard_E,
        [VirtualKey.F] = LedId.Keyboard_F,
        [VirtualKey.G] = LedId.Keyboard_G,
        [VirtualKey.H] = LedId.Keyboard_H,
        [VirtualKey.I] = LedId.Keyboard_I,
        [VirtualKey.J] = LedId.Keyboard_J,
        [VirtualKey.K] = LedId.Keyboard_K,
        [VirtualKey.L] = LedId.Keyboard_L,
        [VirtualKey.M] = LedId.Keyboard_M,
        [VirtualKey.N] = LedId.Keyboard_N,
        [VirtualKey.O] = LedId.Keyboard_O,
        [VirtualKey.P] = LedId.Keyboard_P,
        [VirtualKey.Q] = LedId.Keyboard_Q,
        [VirtualKey.R] = LedId.Keyboard_R,
        [VirtualKey.S] = LedId.Keyboard_S,
        [VirtualKey.T] = LedId.Keyboard_T,
        [VirtualKey.U] = LedId.Keyboard_U,
        [VirtualKey.V] = LedId.Keyboard_V,
        [VirtualKey.W] = LedId.Keyboard_W,
        [VirtualKey.X] = LedId.Keyboard_X,
        [VirtualKey.Y] = LedId.Keyboard_Y,
        [VirtualKey.Z] = LedId.Keyboard_Z,
        [VirtualKey.LeftWindows] = LedId.Keyboard_LeftGui,
        [VirtualKey.RightWindows] = LedId.Keyboard_RightGui,
        [VirtualKey.Application] = LedId.Keyboard_Application,
        [VirtualKey.NumberPad0] = LedId.Keyboard_Num0,
        [VirtualKey.NumberPad1] = LedId.Keyboard_Num1,
        [VirtualKey.NumberPad2] = LedId.Keyboard_Num2,
        [VirtualKey.NumberPad3] = LedId.Keyboard_Num3,
        [VirtualKey.NumberPad4] = LedId.Keyboard_Num4,
        [VirtualKey.NumberPad5] = LedId.Keyboard_Num5,
        [VirtualKey.NumberPad6] = LedId.Keyboard_Num6,
        [VirtualKey.NumberPad7] = LedId.Keyboard_Num7,
        [VirtualKey.NumberPad8] = LedId.Keyboard_Num8,
        [VirtualKey.NumberPad9] = LedId.Keyboard_Num9,
        [VirtualKey.Multiply] = LedId.Keyboard_NumAsterisk,
        [VirtualKey.Add] = LedId.Keyboard_NumPlus,
        [VirtualKey.Subtract] = LedId.Keyboard_NumMinus,
        [VirtualKey.Decimal] = LedId.Keyboard_NumComma,
        [VirtualKey.Divide] = LedId.Keyboard_NumSlash,
        [VirtualKey.F1] = LedId.Keyboard_F1,
        [VirtualKey.F2] = LedId.Keyboard_F2,
        [VirtualKey.F3] = LedId.Keyboard_F3,
        [VirtualKey.F4] = LedId.Keyboard_F4,
        [VirtualKey.F5] = LedId.Keyboard_F5,
        [VirtualKey.F6] = LedId.Keyboard_F6,
        [VirtualKey.F7] = LedId.Keyboard_F7,
        [VirtualKey.F8] = LedId.Keyboard_F8,
        [VirtualKey.F9] = LedId.Keyboard_F9,
        [VirtualKey.F10] = LedId.Keyboard_F10,
        [VirtualKey.F11] = LedId.Keyboard_F11,
        [VirtualKey.F12] = LedId.Keyboard_F12,
        [VirtualKey.NumberKeyLock] = LedId.Keyboard_NumLock,
        [VirtualKey.Scroll] = LedId.Keyboard_ScrollLock,
        [VirtualKey.LeftShift] = LedId.Keyboard_LeftShift,
        [VirtualKey.RightShift] = LedId.Keyboard_RightShift,
        [VirtualKey.LeftControl] = LedId.Keyboard_LeftCtrl,
        [VirtualKey.RightControl] = LedId.Keyboard_RightCtrl,
    };
}